# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/msgs/adcs.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/msgs/adcs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flatsat.msgs import hal_pb2 as flatsat_dot_msgs_dot_hal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66latsat/msgs/adcs.proto\x12\nflatsat.v1\x1a\x16\x66latsat/msgs/hal.proto\"z\n\x12WheelTorqueCommand\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x14\n\x0ctorque_x_n_m\x18\x02 \x01(\x01\x12\x14\n\x0ctorque_y_n_m\x18\x03 \x01(\x01\x12\x14\n\x0ctorque_z_n_m\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.msgs.adcs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WHEELTORQUECOMMAND']._serialized_start=63
  _globals['_WHEELTORQUECOMMAND']._serialized_end=185
# @@protoc_insertion_point(module_scope)
