"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
ADCS actuator command messages (Track A: A1 mock loop onward).

Commands reuse the common Header: sample_time_ns = when the control law
ran, seq = per-source command counter, validity = acquisition facts about
the INPUTS the command was computed from (a command computed from stale
sensor data says so, rather than pretending).
"""

from flatsat.msgs import hal_pb2 as _hal_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class WheelTorqueCommand(_message.Message):
    """Reaction-wheel torque command, body frame, SI units."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    TORQUE_X_N_M_FIELD_NUMBER: _builtins.int
    TORQUE_Y_N_M_FIELD_NUMBER: _builtins.int
    TORQUE_Z_N_M_FIELD_NUMBER: _builtins.int
    torque_x_n_m: _builtins.float
    torque_y_n_m: _builtins.float
    torque_z_n_m: _builtins.float
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        torque_x_n_m: _builtins.float = ...,
        torque_y_n_m: _builtins.float = ...,
        torque_z_n_m: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "torque_x_n_m", b"torque_x_n_m", "torque_y_n_m", b"torque_y_n_m", "torque_z_n_m", b"torque_z_n_m"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WheelTorqueCommand: _TypeAlias = WheelTorqueCommand  # noqa: Y015

@_typing.final
class DipoleCommand(_message.Message):
    """Magnetorquer dipole command, body frame, A·m². Deliberately NOT a
    torque: the achievable torque is m x B and is decided by the plant's
    local field, never by the control law's request.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    DIPOLE_X_A_M2_FIELD_NUMBER: _builtins.int
    DIPOLE_Y_A_M2_FIELD_NUMBER: _builtins.int
    DIPOLE_Z_A_M2_FIELD_NUMBER: _builtins.int
    dipole_x_a_m2: _builtins.float
    dipole_y_a_m2: _builtins.float
    dipole_z_a_m2: _builtins.float
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        dipole_x_a_m2: _builtins.float = ...,
        dipole_y_a_m2: _builtins.float = ...,
        dipole_z_a_m2: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dipole_x_a_m2", b"dipole_x_a_m2", "dipole_y_a_m2", b"dipole_y_a_m2", "dipole_z_a_m2", b"dipole_z_a_m2", "header", b"header"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DipoleCommand: _TypeAlias = DipoleCommand  # noqa: Y015
