"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Process health telemetry — the system's own vital signs, as DATA.

Previously these numbers existed only as printf into the journal:
unparseable, unrecordable, invisible to FDIR, useless for regression
analysis. A flight system's own timing and validity statistics are
telemetry like any other measurement, so they are messages.

Every field here is something a later consumer needs: the recorder
archives it, FDIR limit-checks it (jitter climbing, stale ratio rising),
the anomaly corpus learns from it, and a regression test compares runs.
Config provenance travels WITH the numbers so a recorded window can
always be traced to the parameters that produced it.
"""

from collections import abc as _abc
from flatsat.msgs import hal_pb2 as _hal_pb2
from flatsat.msgs import mode_pb2 as _mode_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Percentiles(_message.Message):
    """Distribution summary of a per-cycle measurement over one window."""

    DESCRIPTOR: _descriptor.Descriptor

    P50_FIELD_NUMBER: _builtins.int
    P99_FIELD_NUMBER: _builtins.int
    P99_9_FIELD_NUMBER: _builtins.int
    MAX_FIELD_NUMBER: _builtins.int
    COUNT_FIELD_NUMBER: _builtins.int
    p50: _builtins.float
    p99: _builtins.float
    p99_9: _builtins.float
    max: _builtins.float
    count: _builtins.int
    def __init__(
        self,
        *,
        p50: _builtins.float = ...,
        p99: _builtins.float = ...,
        p99_9: _builtins.float = ...,
        max: _builtins.float = ...,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "max", b"max", "p50", b"p50", "p99", b"p99", "p99_9", b"p99_9"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Percentiles: _TypeAlias = Percentiles  # noqa: Y015

@_typing.final
class LoopHealth(_message.Message):
    """Health of a control loop over one reporting window."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    VEHICLE_FIELD_NUMBER: _builtins.int
    CONFIG_CHECKSUM_FIELD_NUMBER: _builtins.int
    STRATEGY_FIELD_NUMBER: _builtins.int
    OBJECTIVE_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    SCHEDULING_FIELD_NUMBER: _builtins.int
    CPU_AFFINITY_FIELD_NUMBER: _builtins.int
    WINDOW_CYCLES_FIELD_NUMBER: _builtins.int
    STALE_CYCLES_FIELD_NUMBER: _builtins.int
    SATURATED_CYCLES_FIELD_NUMBER: _builtins.int
    WAKEUP_LATENESS_US_FIELD_NUMBER: _builtins.int
    EXEC_TIME_US_FIELD_NUMBER: _builtins.int
    SATURATED_TORQUE_CYCLES_FIELD_NUMBER: _builtins.int
    SATURATED_DIPOLE_CYCLES_FIELD_NUMBER: _builtins.int
    vehicle: _builtins.str
    """Composition provenance: what was flying, configured by what."""
    config_checksum: _builtins.str
    strategy: _builtins.str
    objective: _builtins.str
    rate_hz: _builtins.float
    scheduling: _builtins.str
    """Execution environment actually in force (verified, not requested).
    e.g. "SCHED_FIFO priority 80"
    """
    cpu_affinity: _builtins.str
    """e.g. "3" """
    window_cycles: _builtins.int
    """Window counters."""
    stale_cycles: _builtins.int
    """ran on an input older than the threshold"""
    saturated_cycles: _builtins.int
    """ANY command clipped (union of the two below)"""
    saturated_torque_cycles: _builtins.int
    """Saturation split by channel: a railed rod is momentum management
    running at its ceiling (normal for hours); a railed wheel is
    attitude authority lost (a fault precursor). One number hid that
    distinction on the combined vehicles.
    """
    saturated_dipole_cycles: _builtins.int
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    @_builtins.property
    def wakeup_lateness_us(self) -> Global___Percentiles:
        """Timing distributions, microseconds."""

    @_builtins.property
    def exec_time_us(self) -> Global___Percentiles: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        vehicle: _builtins.str = ...,
        config_checksum: _builtins.str = ...,
        strategy: _builtins.str = ...,
        objective: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        scheduling: _builtins.str = ...,
        cpu_affinity: _builtins.str = ...,
        window_cycles: _builtins.int = ...,
        stale_cycles: _builtins.int = ...,
        saturated_cycles: _builtins.int = ...,
        wakeup_lateness_us: Global___Percentiles | None = ...,
        exec_time_us: Global___Percentiles | None = ...,
        saturated_torque_cycles: _builtins.int = ...,
        saturated_dipole_cycles: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["exec_time_us", b"exec_time_us", "header", b"header", "wakeup_lateness_us", b"wakeup_lateness_us"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_checksum", b"config_checksum", "cpu_affinity", b"cpu_affinity", "exec_time_us", b"exec_time_us", "header", b"header", "objective", b"objective", "rate_hz", b"rate_hz", "saturated_cycles", b"saturated_cycles", "saturated_dipole_cycles", b"saturated_dipole_cycles", "saturated_torque_cycles", b"saturated_torque_cycles", "scheduling", b"scheduling", "stale_cycles", b"stale_cycles", "strategy", b"strategy", "vehicle", b"vehicle", "wakeup_lateness_us", b"wakeup_lateness_us", "window_cycles", b"window_cycles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LoopHealth: _TypeAlias = LoopHealth  # noqa: Y015

@_typing.final
class SensorHealth(_message.Message):
    """Health of a sensor daemon over one reporting window."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    DRIVER_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    WINDOW_SAMPLES_FIELD_NUMBER: _builtins.int
    FLAGGED_SAMPLES_FIELD_NUMBER: _builtins.int
    FLAG_UNION_FIELD_NUMBER: _builtins.int
    driver: _builtins.str
    rate_hz: _builtins.float
    window_samples: _builtins.int
    flagged_samples: _builtins.int
    """samples with any validity flag set"""
    flag_union: _builtins.int
    """bitwise OR of every flag seen in the window"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        driver: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        window_samples: _builtins.int = ...,
        flagged_samples: _builtins.int = ...,
        flag_union: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["driver", b"driver", "flag_union", b"flag_union", "flagged_samples", b"flagged_samples", "header", b"header", "rate_hz", b"rate_hz", "window_samples", b"window_samples"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SensorHealth: _TypeAlias = SensorHealth  # noqa: Y015

@_typing.final
class ActuatorHealth(_message.Message):
    """Health of an actuator daemon over one reporting window."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    DRIVER_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    WINDOW_CYCLES_FIELD_NUMBER: _builtins.int
    STALE_ZEROED_CYCLES_FIELD_NUMBER: _builtins.int
    FLAGGED_CYCLES_FIELD_NUMBER: _builtins.int
    FLAG_UNION_FIELD_NUMBER: _builtins.int
    driver: _builtins.str
    rate_hz: _builtins.float
    window_cycles: _builtins.int
    stale_zeroed_cycles: _builtins.int
    """cycles zeroed for want of a fresh command"""
    flagged_cycles: _builtins.int
    """cycles where apply()/state() raised a flag"""
    flag_union: _builtins.int
    """bitwise OR of every flag seen in the window"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        driver: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        window_cycles: _builtins.int = ...,
        stale_zeroed_cycles: _builtins.int = ...,
        flagged_cycles: _builtins.int = ...,
        flag_union: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["driver", b"driver", "flag_union", b"flag_union", "flagged_cycles", b"flagged_cycles", "header", b"header", "rate_hz", b"rate_hz", "stale_zeroed_cycles", b"stale_zeroed_cycles", "window_cycles", b"window_cycles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActuatorHealth: _TypeAlias = ActuatorHealth  # noqa: Y015

@_typing.final
class RecorderHealth(_message.Message):
    """Health of the telemetry recorder over one reporting window."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    WINDOW_RECORDS_FIELD_NUMBER: _builtins.int
    WINDOW_BYTES_FIELD_NUMBER: _builtins.int
    FILES_FIELD_NUMBER: _builtins.int
    TOTAL_BYTES_FIELD_NUMBER: _builtins.int
    CURRENT_FILE_FIELD_NUMBER: _builtins.int
    window_records: _builtins.int
    """messages recorded this window"""
    window_bytes: _builtins.int
    """bytes appended this window"""
    files: _builtins.int
    """archive files currently on disk"""
    total_bytes: _builtins.int
    """archive size currently on disk"""
    current_file: _builtins.str
    """basename of the file being written"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        window_records: _builtins.int = ...,
        window_bytes: _builtins.int = ...,
        files: _builtins.int = ...,
        total_bytes: _builtins.int = ...,
        current_file: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current_file", b"current_file", "files", b"files", "header", b"header", "total_bytes", b"total_bytes", "window_bytes", b"window_bytes", "window_records", b"window_records"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RecorderHealth: _TypeAlias = RecorderHealth  # noqa: Y015

@_typing.final
class ModeHealth(_message.Message):
    """Health of the mode manager over one reporting window."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    MODE_SEQ_FIELD_NUMBER: _builtins.int
    TRANSITIONS_FIELD_NUMBER: _builtins.int
    REJECTED_REQUESTS_FIELD_NUMBER: _builtins.int
    SAFE_ENTRIES_FIELD_NUMBER: _builtins.int
    MISSING_ACKS_FIELD_NUMBER: _builtins.int
    mode: _mode_pb2.SystemMode.ValueType
    mode_seq: _builtins.int
    transitions: _builtins.int
    """accepted transitions since start"""
    rejected_requests: _builtins.int
    """requests refused (authority, matrix, dwell)"""
    safe_entries: _builtins.int
    """times SAFE has been entered (flap escalation input)"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    @_builtins.property
    def missing_acks(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """apps that did not ack the current seq in time"""

    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        mode: _mode_pb2.SystemMode.ValueType = ...,
        mode_seq: _builtins.int = ...,
        transitions: _builtins.int = ...,
        rejected_requests: _builtins.int = ...,
        safe_entries: _builtins.int = ...,
        missing_acks: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "missing_acks", b"missing_acks", "mode", b"mode", "mode_seq", b"mode_seq", "rejected_requests", b"rejected_requests", "safe_entries", b"safe_entries", "transitions", b"transitions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModeHealth: _TypeAlias = ModeHealth  # noqa: Y015

@_typing.final
class FdirHealth(_message.Message):
    """Health of the FDIR service over one reporting window."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    RULES_FIELD_NUMBER: _builtins.int
    TRIPPED_FIELD_NUMBER: _builtins.int
    SAFE_REQUESTS_FIELD_NUMBER: _builtins.int
    rules: _builtins.int
    """rules loaded from the vehicle file"""
    safe_requests: _builtins.int
    """safings requested since start"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    @_builtins.property
    def tripped(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """rules currently tripped"""

    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        rules: _builtins.int = ...,
        tripped: _abc.Iterable[_builtins.str] | None = ...,
        safe_requests: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "rules", b"rules", "safe_requests", b"safe_requests", "tripped", b"tripped"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FdirHealth: _TypeAlias = FdirHealth  # noqa: Y015

@_typing.final
class LinkHealth(_message.Message):
    """Health of the link service over one reporting window."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    IN_CONTACT_FIELD_NUMBER: _builtins.int
    QUEUED_MESSAGES_FIELD_NUMBER: _builtins.int
    FRAMES_SENT_FIELD_NUMBER: _builtins.int
    FRAMES_RECEIVED_FIELD_NUMBER: _builtins.int
    FRAMES_DROPPED_CRC_FIELD_NUMBER: _builtins.int
    MESSAGES_DELIVERED_FIELD_NUMBER: _builtins.int
    MESSAGES_INCOMPLETE_FIELD_NUMBER: _builtins.int
    in_contact: _builtins.bool
    """inside a pass window right now"""
    queued_messages: _builtins.int
    """stored, awaiting the next contact"""
    frames_sent: _builtins.int
    frames_received: _builtins.int
    frames_dropped_crc: _builtins.int
    """corrupted frames the framer rejected"""
    messages_delivered: _builtins.int
    """fully reassembled and republished"""
    messages_incomplete: _builtins.int
    """aged out with segments missing"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        in_contact: _builtins.bool = ...,
        queued_messages: _builtins.int = ...,
        frames_sent: _builtins.int = ...,
        frames_received: _builtins.int = ...,
        frames_dropped_crc: _builtins.int = ...,
        messages_delivered: _builtins.int = ...,
        messages_incomplete: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["frames_dropped_crc", b"frames_dropped_crc", "frames_received", b"frames_received", "frames_sent", b"frames_sent", "header", b"header", "in_contact", b"in_contact", "messages_delivered", b"messages_delivered", "messages_incomplete", b"messages_incomplete", "queued_messages", b"queued_messages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LinkHealth: _TypeAlias = LinkHealth  # noqa: Y015
