"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Link-layer wire contract — what actually crosses the RF link.

The middleware is NEVER tunneled over the space link (PLAN §6):
discovery chatter and reliable-QoS retransmission would melt down on
an intermittent, high-BER, mostly-absent pipe. Instead the link
service explicitly carries NAMED bus messages as datagrams, stores
them between passes, and transmits during contact windows; the ground
mirror deframes and republishes. To every other process the link is
invisible; underneath it is a managed store-and-forward pipe.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LinkSegment(_message.Message):
    """One segment of one logical message. Large payloads (a model artifact,
    a telemetry batch) span many segments; small ones are a single
    segment with total = 1. Segments are the unit the PHY carries, so a
    corrupted frame costs one segment, not the whole message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    TOTAL_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    CHUNK_FIELD_NUMBER: _builtins.int
    message_id: _builtins.int
    """per-sender message counter"""
    index: _builtins.int
    """0-based segment index"""
    total: _builtins.int
    """segments in this message"""
    topic: _builtins.str
    """destination bus key on the far side"""
    chunk: _builtins.bytes
    """this segment's slice of the payload"""
    def __init__(
        self,
        *,
        message_id: _builtins.int = ...,
        index: _builtins.int = ...,
        total: _builtins.int = ...,
        topic: _builtins.str = ...,
        chunk: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "index", b"index", "message_id", b"message_id", "topic", b"topic", "total", b"total"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LinkSegment: _TypeAlias = LinkSegment  # noqa: Y015
