# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/msgs/link.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/msgs/link.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66latsat/msgs/link.proto\x12\nflatsat.v1\"]\n\x0bLinkSegment\x12\x12\n\nmessage_id\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\r\x12\r\n\x05total\x18\x03 \x01(\r\x12\r\n\x05topic\x18\x04 \x01(\t\x12\r\n\x05\x63hunk\x18\x05 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.msgs.link_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINKSEGMENT']._serialized_start=39
  _globals['_LINKSEGMENT']._serialized_end=132
# @@protoc_insertion_point(module_scope)
