"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Mission-level structure for the telemetry archive.

The recorder below this captures a flat, verbatim stream of bus
messages — excellent evidence, but it cannot answer "what was the
spacecraft DOING at 14:32". These messages add that structure without
changing the archive format: they are ordinary bus messages, so they
land in the same stream as everything else and the recording becomes
SELF-DESCRIBING. No sidecar file to lose, no index to rebuild, and
slicing a run by sub-mission works from the archive alone.

Two shapes, and the distinction is deliberate:

  * A Span is an INTERVAL — it has a start and an end, and it nests.
    "Nominal pointing" contains "ml inference"; an outer keep-alive
    span contains everything. Concurrent activities are simply
    overlapping spans, which is what makes a swimlane view possible.
  * An Annotation is a POINT event — a mode change, an FDIR trip, a
    command, a judgment.

The reason commands are annotations rather than span boundaries: a
span is defined by the STATE it represents, not by activity within
it. If every command started a new span you would get thousands of
one-second fragments and lose the thing worth looking at. A command
that changes mode does end a span — but because it changed the state,
not because it was a command.
"""

from collections import abc as _abc
from flatsat.msgs import hal_pb2 as _hal_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SourceKind:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SourceKindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SourceKind.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SOURCE_KIND_UNSPECIFIED: _SourceKind.ValueType  # 0
    SOURCE_KIND_SIM: _SourceKind.ValueType  # 1
    """synthetic plant, no hardware in the loop"""
    SOURCE_KIND_HIL: _SourceKind.ValueType  # 2
    """real flight software against a simulated universe"""
    SOURCE_KIND_FLIGHT: _SourceKind.ValueType  # 3
    """real vehicle, real devices"""
    SOURCE_KIND_REPLAY: _SourceKind.ValueType  # 4
    """re-derived from an earlier archive"""

class SourceKind(_SourceKind, metaclass=_SourceKindEnumTypeWrapper):
    """How the data in a session was produced. This is the single most
    valuable field in the archive: sim, hardware-in-the-loop and flight
    runs publish IDENTICAL topics by design, which is what lets the same
    software fly all three — and is exactly why a recording must say
    which one it was. Without it, two runs are indistinguishable.
    """

SOURCE_KIND_UNSPECIFIED: SourceKind.ValueType  # 0
SOURCE_KIND_SIM: SourceKind.ValueType  # 1
"""synthetic plant, no hardware in the loop"""
SOURCE_KIND_HIL: SourceKind.ValueType  # 2
"""real flight software against a simulated universe"""
SOURCE_KIND_FLIGHT: SourceKind.ValueType  # 3
"""real vehicle, real devices"""
SOURCE_KIND_REPLAY: SourceKind.ValueType  # 4
"""re-derived from an earlier archive"""
Global___SourceKind: _TypeAlias = SourceKind  # noqa: Y015

class _SpanKind:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SpanKindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SpanKind.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPAN_KIND_UNSPECIFIED: _SpanKind.ValueType  # 0
    SPAN_KIND_MISSION: _SpanKind.ValueType  # 1
    """the whole run"""
    SPAN_KIND_PHASE: _SpanKind.ValueType  # 2
    """a sub-mission"""
    SPAN_KIND_ACTIVITY: _SpanKind.ValueType  # 3
    """anything finer: an app, a pass, an inference batch"""

class SpanKind(_SpanKind, metaclass=_SpanKindEnumTypeWrapper): ...

SPAN_KIND_UNSPECIFIED: SpanKind.ValueType  # 0
SPAN_KIND_MISSION: SpanKind.ValueType  # 1
"""the whole run"""
SPAN_KIND_PHASE: SpanKind.ValueType  # 2
"""a sub-mission"""
SPAN_KIND_ACTIVITY: SpanKind.ValueType  # 3
"""anything finer: an app, a pass, an inference batch"""
Global___SpanKind: _TypeAlias = SpanKind  # noqa: Y015

@_typing.final
class SessionHeader(_message.Message):
    """Written as the FIRST record of every archive file, so a file is
    interpretable on its own. Files rotate and the oldest are pruned, so
    metadata held only at the start of a run would be the first thing
    lost.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    RUN_ID_FIELD_NUMBER: _builtins.int
    SOURCE_KIND_FIELD_NUMBER: _builtins.int
    MISSION_NAME_FIELD_NUMBER: _builtins.int
    VEHICLE_PATH_FIELD_NUMBER: _builtins.int
    VEHICLE_SHA256_FIELD_NUMBER: _builtins.int
    GIT_SHA_FIELD_NUMBER: _builtins.int
    GIT_DIRTY_FIELD_NUMBER: _builtins.int
    PLANT_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    STARTED_WALL_NS_FIELD_NUMBER: _builtins.int
    STARTED_MONO_NS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """one execution; the join key across files"""
    source_kind: Global___SourceKind.ValueType
    mission_name: _builtins.str
    """empty when the run is not a mission"""
    vehicle_path: _builtins.str
    vehicle_sha256: _builtins.str
    """the composition as flown, not as it reads today"""
    git_sha: _builtins.str
    git_dirty: _builtins.bool
    """uncommitted changes: the run is not reproducible"""
    plant: _builtins.str
    """rigid, basilisk, none"""
    host: _builtins.str
    started_wall_ns: _builtins.int
    """wall clock, for correlating with the world"""
    started_mono_ns: _builtins.int
    """monotonic, for correlating within the run"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header:
        """keeps "every payload starts with a Header" true"""

    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        run_id: _builtins.str = ...,
        source_kind: Global___SourceKind.ValueType = ...,
        mission_name: _builtins.str = ...,
        vehicle_path: _builtins.str = ...,
        vehicle_sha256: _builtins.str = ...,
        git_sha: _builtins.str = ...,
        git_dirty: _builtins.bool = ...,
        plant: _builtins.str = ...,
        host: _builtins.str = ...,
        started_wall_ns: _builtins.int = ...,
        started_mono_ns: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["git_dirty", b"git_dirty", "git_sha", b"git_sha", "header", b"header", "host", b"host", "mission_name", b"mission_name", "plant", b"plant", "run_id", b"run_id", "source_kind", b"source_kind", "started_mono_ns", b"started_mono_ns", "started_wall_ns", b"started_wall_ns", "vehicle_path", b"vehicle_path", "vehicle_sha256", b"vehicle_sha256"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionHeader: _TypeAlias = SessionHeader  # noqa: Y015

@_typing.final
class Span(_message.Message):
    """One edge of an interval. Start and end are separate messages rather
    than one message with a duration, because a run that dies mid-phase
    must still leave evidence of what it was doing — an unclosed span is
    itself the finding.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AttributesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    HEADER_FIELD_NUMBER: _builtins.int
    SPAN_ID_FIELD_NUMBER: _builtins.int
    PARENT_SPAN_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    OPEN_FIELD_NUMBER: _builtins.int
    TIME_NS_FIELD_NUMBER: _builtins.int
    OUTCOME_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    ATTRIBUTES_FIELD_NUMBER: _builtins.int
    span_id: _builtins.str
    parent_span_id: _builtins.str
    """empty = root; nesting is what makes the tree"""
    kind: Global___SpanKind.ValueType
    name: _builtins.str
    open: _builtins.bool
    """true = this edge opens the span, false = closes"""
    time_ns: _builtins.int
    outcome: _builtins.str
    """on close: pass, fail, aborted; empty otherwise"""
    detail: _builtins.str
    """why, in one line"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    @_builtins.property
    def attributes(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        span_id: _builtins.str = ...,
        parent_span_id: _builtins.str = ...,
        kind: Global___SpanKind.ValueType = ...,
        name: _builtins.str = ...,
        open: _builtins.bool = ...,
        time_ns: _builtins.int = ...,
        outcome: _builtins.str = ...,
        detail: _builtins.str = ...,
        attributes: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attributes", b"attributes", "detail", b"detail", "header", b"header", "kind", b"kind", "name", b"name", "open", b"open", "outcome", b"outcome", "parent_span_id", b"parent_span_id", "span_id", b"span_id", "time_ns", b"time_ns"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Span: _TypeAlias = Span  # noqa: Y015

@_typing.final
class Annotation(_message.Message):
    """A point event on the timeline."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    TIME_NS_FIELD_NUMBER: _builtins.int
    SPAN_ID_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    time_ns: _builtins.int
    span_id: _builtins.str
    """which span it happened inside; empty = unattributed"""
    level: _builtins.str
    """info, warn, error"""
    source: _builtins.str
    """which organ said it: mode, fdir, ground, runner"""
    message: _builtins.str
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        time_ns: _builtins.int = ...,
        span_id: _builtins.str = ...,
        level: _builtins.str = ...,
        source: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "level", b"level", "message", b"message", "source", b"source", "span_id", b"span_id", "time_ns", b"time_ns"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Annotation: _TypeAlias = Annotation  # noqa: Y015
