# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/msgs/mission_log.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/msgs/mission_log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flatsat.msgs import hal_pb2 as flatsat_dot_msgs_dot_hal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66latsat/msgs/mission_log.proto\x12\nflatsat.v1\x1a\x16\x66latsat/msgs/hal.proto\"\xa7\x02\n\rSessionHeader\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12+\n\x0bsource_kind\x18\x03 \x01(\x0e\x32\x16.flatsat.v1.SourceKind\x12\x14\n\x0cmission_name\x18\x04 \x01(\t\x12\x14\n\x0cvehicle_path\x18\x05 \x01(\t\x12\x16\n\x0evehicle_sha256\x18\x06 \x01(\t\x12\x0f\n\x07git_sha\x18\x07 \x01(\t\x12\x11\n\tgit_dirty\x18\x08 \x01(\x08\x12\r\n\x05plant\x18\t \x01(\t\x12\x0c\n\x04host\x18\n \x01(\t\x12\x17\n\x0fstarted_wall_ns\x18\x0b \x01(\x06\x12\x17\n\x0fstarted_mono_ns\x18\x0c \x01(\x06\"\xae\x02\n\x04Span\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x0f\n\x07span_id\x18\x02 \x01(\t\x12\x16\n\x0eparent_span_id\x18\x03 \x01(\t\x12\"\n\x04kind\x18\x04 \x01(\x0e\x32\x14.flatsat.v1.SpanKind\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0c\n\x04open\x18\x06 \x01(\x08\x12\x0f\n\x07time_ns\x18\x07 \x01(\x06\x12\x0f\n\x07outcome\x18\x08 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\t \x01(\t\x12\x34\n\nattributes\x18\n \x03(\x0b\x32 .flatsat.v1.Span.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x82\x01\n\nAnnotation\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x0f\n\x07time_ns\x18\x02 \x01(\x06\x12\x0f\n\x07span_id\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t*\x83\x01\n\nSourceKind\x12\x1b\n\x17SOURCE_KIND_UNSPECIFIED\x10\x00\x12\x13\n\x0fSOURCE_KIND_SIM\x10\x01\x12\x13\n\x0fSOURCE_KIND_HIL\x10\x02\x12\x16\n\x12SOURCE_KIND_FLIGHT\x10\x03\x12\x16\n\x12SOURCE_KIND_REPLAY\x10\x04*i\n\x08SpanKind\x12\x19\n\x15SPAN_KIND_UNSPECIFIED\x10\x00\x12\x15\n\x11SPAN_KIND_MISSION\x10\x01\x12\x13\n\x0fSPAN_KIND_PHASE\x10\x02\x12\x16\n\x12SPAN_KIND_ACTIVITY\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.msgs.mission_log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPAN_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_SPAN_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_SOURCEKIND']._serialized_start=807
  _globals['_SOURCEKIND']._serialized_end=938
  _globals['_SPANKIND']._serialized_start=940
  _globals['_SPANKIND']._serialized_end=1045
  _globals['_SESSIONHEADER']._serialized_start=71
  _globals['_SESSIONHEADER']._serialized_end=366
  _globals['_SPAN']._serialized_start=369
  _globals['_SPAN']._serialized_end=671
  _globals['_SPAN_ATTRIBUTESENTRY']._serialized_start=622
  _globals['_SPAN_ATTRIBUTESENTRY']._serialized_end=671
  _globals['_ANNOTATION']._serialized_start=674
  _globals['_ANNOTATION']._serialized_end=804
# @@protoc_insertion_point(module_scope)
