"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
System mode state (PLAN.md §7).

Published latched on sys/mode with a monotonic sequence and reason; every
registered app must ack the sequence within a timeout. Toward-safety
transitions are automatic; away-from-safety is ground-command-only.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SystemMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SystemModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SystemMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SYSTEM_MODE_UNSPECIFIED: _SystemMode.ValueType  # 0
    SYSTEM_MODE_INIT: _SystemMode.ValueType  # 1
    SYSTEM_MODE_NOMINAL: _SystemMode.ValueType  # 2
    SYSTEM_MODE_SAFE: _SystemMode.ValueType  # 3
    SYSTEM_MODE_RECOVERY: _SystemMode.ValueType  # 4

class SystemMode(_SystemMode, metaclass=_SystemModeEnumTypeWrapper):
    """The four flat states. Orthogonal conditions (in-contact, sim-fed) are
    flags on other topics, never modes.
    """

SYSTEM_MODE_UNSPECIFIED: SystemMode.ValueType  # 0
SYSTEM_MODE_INIT: SystemMode.ValueType  # 1
SYSTEM_MODE_NOMINAL: SystemMode.ValueType  # 2
SYSTEM_MODE_SAFE: SystemMode.ValueType  # 3
SYSTEM_MODE_RECOVERY: SystemMode.ValueType  # 4
Global___SystemMode: _TypeAlias = SystemMode  # noqa: Y015

@_typing.final
class ModeState(_message.Message):
    """Latched mode state: the current mode plus the transition that produced it."""

    DESCRIPTOR: _descriptor.Descriptor

    MODE_FIELD_NUMBER: _builtins.int
    MODE_SEQ_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    TRANSITION_TIME_NS_FIELD_NUMBER: _builtins.int
    mode: Global___SystemMode.ValueType
    mode_seq: _builtins.int
    """monotonic transition counter; acks cite it"""
    reason: _builtins.str
    """cause of the last transition"""
    transition_time_ns: _builtins.int
    """flight-clock time of the transition"""
    def __init__(
        self,
        *,
        mode: Global___SystemMode.ValueType = ...,
        mode_seq: _builtins.int = ...,
        reason: _builtins.str = ...,
        transition_time_ns: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mode", b"mode", "mode_seq", b"mode_seq", "reason", b"reason", "transition_time_ns", b"transition_time_ns"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModeState: _TypeAlias = ModeState  # noqa: Y015

@_typing.final
class ModeRequest(_message.Message):
    """Request to change the system mode, published on sys/mode/request.

    The authority asymmetry lives in the manager's transition rules:
    toward safety needs no authority (FDIR, watchdogs, anyone); away from
    safety is honored only with ground_authority set.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FIELD_NUMBER: _builtins.int
    REQUESTED_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    GROUND_AUTHORITY_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    """requesting component, e.g. "fdir", "ground" """
    requested: Global___SystemMode.ValueType
    reason: _builtins.str
    ground_authority: _builtins.bool
    """true only for ground-commanded requests"""
    def __init__(
        self,
        *,
        source: _builtins.str = ...,
        requested: Global___SystemMode.ValueType = ...,
        reason: _builtins.str = ...,
        ground_authority: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ground_authority", b"ground_authority", "reason", b"reason", "requested", b"requested", "source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModeRequest: _TypeAlias = ModeRequest  # noqa: Y015

@_typing.final
class ModeAck(_message.Message):
    """One app's acknowledgement of a mode transition, on sys/mode/ack.
    A missing ack within the timeout is itself a fault the manager surfaces.
    """

    DESCRIPTOR: _descriptor.Descriptor

    APP_FIELD_NUMBER: _builtins.int
    MODE_SEQ_FIELD_NUMBER: _builtins.int
    app: _builtins.str
    mode_seq: _builtins.int
    """the transition being acknowledged"""
    def __init__(
        self,
        *,
        app: _builtins.str = ...,
        mode_seq: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app", b"app", "mode_seq", b"mode_seq"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModeAck: _TypeAlias = ModeAck  # noqa: Y015
