# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/msgs/mode.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/msgs/mode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66latsat/msgs/mode.proto\x12\nflatsat.v1\"o\n\tModeState\x12$\n\x04mode\x18\x01 \x01(\x0e\x32\x16.flatsat.v1.SystemMode\x12\x10\n\x08mode_seq\x18\x02 \x01(\x04\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x1a\n\x12transition_time_ns\x18\x04 \x01(\x06\"r\n\x0bModeRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12)\n\trequested\x18\x02 \x01(\x0e\x32\x16.flatsat.v1.SystemMode\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x18\n\x10ground_authority\x18\x04 \x01(\x08\"(\n\x07ModeAck\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\x12\x10\n\x08mode_seq\x18\x02 \x01(\x04*\x88\x01\n\nSystemMode\x12\x1b\n\x17SYSTEM_MODE_UNSPECIFIED\x10\x00\x12\x14\n\x10SYSTEM_MODE_INIT\x10\x01\x12\x17\n\x13SYSTEM_MODE_NOMINAL\x10\x02\x12\x14\n\x10SYSTEM_MODE_SAFE\x10\x03\x12\x18\n\x14SYSTEM_MODE_RECOVERY\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.msgs.mode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMMODE']._serialized_start=311
  _globals['_SYSTEMMODE']._serialized_end=447
  _globals['_MODESTATE']._serialized_start=39
  _globals['_MODESTATE']._serialized_end=150
  _globals['_MODEREQUEST']._serialized_start=152
  _globals['_MODEREQUEST']._serialized_end=266
  _globals['_MODEACK']._serialized_start=268
  _globals['_MODEACK']._serialized_end=308
# @@protoc_insertion_point(module_scope)
