"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Simulation bridge contract — the seam between the universe-fake and the
basilisk_* device drivers.

The bridge (flatsat/sim/basilisk_hil.py, ground machine) publishes TRUTH;
the flight-side basilisk_* drivers corrupt truth through the shared
device models and feed it to the ordinary daemons. Flight software never
consumes these topics directly — only drivers do. Truth is exactly what
a robustness campaign later perturbs on purpose (truth_overrides).
"""

from flatsat.msgs import hal_pb2 as _hal_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TruthState(_message.Message):
    """Rigid-body truth from the physics engine, one message per sim step."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    OMEGA_X_RAD_S_FIELD_NUMBER: _builtins.int
    OMEGA_Y_RAD_S_FIELD_NUMBER: _builtins.int
    OMEGA_Z_RAD_S_FIELD_NUMBER: _builtins.int
    SIGMA_X_FIELD_NUMBER: _builtins.int
    SIGMA_Y_FIELD_NUMBER: _builtins.int
    SIGMA_Z_FIELD_NUMBER: _builtins.int
    POSITION_X_M_FIELD_NUMBER: _builtins.int
    POSITION_Y_M_FIELD_NUMBER: _builtins.int
    POSITION_Z_M_FIELD_NUMBER: _builtins.int
    MAG_FIELD_X_T_FIELD_NUMBER: _builtins.int
    MAG_FIELD_Y_T_FIELD_NUMBER: _builtins.int
    MAG_FIELD_Z_T_FIELD_NUMBER: _builtins.int
    IN_ECLIPSE_FIELD_NUMBER: _builtins.int
    omega_x_rad_s: _builtins.float
    """true body rates"""
    omega_y_rad_s: _builtins.float
    omega_z_rad_s: _builtins.float
    sigma_x: _builtins.float
    """true attitude, MRP (sigma_BN)"""
    sigma_y: _builtins.float
    sigma_z: _builtins.float
    position_x_m: _builtins.float
    """Inertial position. Absent (all zero) when the run has no orbit."""
    position_y_m: _builtins.float
    position_z_m: _builtins.float
    mag_field_x_t: _builtins.float
    """Geomagnetic field in the BODY frame, which is what a magnetometer
    measures and what magnetorquer torque (m x B) is computed in.
    Publishing it inertially would push the same rotation into every
    consumer.
    """
    mag_field_y_t: _builtins.float
    mag_field_z_t: _builtins.float
    in_eclipse: _builtins.bool
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        omega_x_rad_s: _builtins.float = ...,
        omega_y_rad_s: _builtins.float = ...,
        omega_z_rad_s: _builtins.float = ...,
        sigma_x: _builtins.float = ...,
        sigma_y: _builtins.float = ...,
        sigma_z: _builtins.float = ...,
        position_x_m: _builtins.float = ...,
        position_y_m: _builtins.float = ...,
        position_z_m: _builtins.float = ...,
        mag_field_x_t: _builtins.float = ...,
        mag_field_y_t: _builtins.float = ...,
        mag_field_z_t: _builtins.float = ...,
        in_eclipse: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "in_eclipse", b"in_eclipse", "mag_field_x_t", b"mag_field_x_t", "mag_field_y_t", b"mag_field_y_t", "mag_field_z_t", b"mag_field_z_t", "omega_x_rad_s", b"omega_x_rad_s", "omega_y_rad_s", b"omega_y_rad_s", "omega_z_rad_s", b"omega_z_rad_s", "position_x_m", b"position_x_m", "position_y_m", b"position_y_m", "position_z_m", b"position_z_m", "sigma_x", b"sigma_x", "sigma_y", b"sigma_y", "sigma_z", b"sigma_z"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TruthState: _TypeAlias = TruthState  # noqa: Y015

@_typing.final
class WheelAxisTorque(_message.Message):
    """Torque one wheel is actually applying about its own spin axis,
    published by the basilisk_reaction_wheel driver AFTER its device
    envelopes — the sim feels what the device could actually do, not what
    was asked of it. The bridge maps it into the body frame through the
    SAME vehicle-file mounting the flight side used.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    WHEEL_FIELD_NUMBER: _builtins.int
    TORQUE_N_M_FIELD_NUMBER: _builtins.int
    wheel: _builtins.str
    """actuator instance name, sanity check vs topic"""
    torque_n_m: _builtins.float
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        wheel: _builtins.str = ...,
        torque_n_m: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "torque_n_m", b"torque_n_m", "wheel", b"wheel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WheelAxisTorque: _TypeAlias = WheelAxisTorque  # noqa: Y015

@_typing.final
class MagnetorquerDipole(_message.Message):
    """Dipole one magnetorquer rod is actually driving along its own axis,
    published by the basilisk_magnetorquer driver AFTER its device
    envelope. The plant maps it into the body frame through the vehicle
    file's mounting and computes torque m x B from ITS OWN local field —
    a rod never tells the universe how much torque it produced.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    ROD_FIELD_NUMBER: _builtins.int
    DIPOLE_A_M2_FIELD_NUMBER: _builtins.int
    rod: _builtins.str
    """actuator instance name, sanity check vs topic"""
    dipole_a_m2: _builtins.float
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        rod: _builtins.str = ...,
        dipole_a_m2: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dipole_a_m2", b"dipole_a_m2", "header", b"header", "rod", b"rod"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MagnetorquerDipole: _TypeAlias = MagnetorquerDipole  # noqa: Y015
