"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Telemetry recording format — the archive every later consumer reads.

The recorder stores bus traffic VERBATIM: topic, arrival time, and the
exact payload bytes that were on the wire. It never parses payloads —
a new message type or topic needs no recorder change, and the archive
is byte-exact evidence of what the bus carried (regression comparison,
FDIR replay, and the ML corpus all read from here).

On disk: a stream of [4-byte little-endian length][RecordedSample]
frames. A truncated final frame (power loss mid-write) is expected and
readers must treat it as end-of-file, not corruption of the archive.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RecordedSample(_message.Message):
    """One bus message as the recorder saw it."""

    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_FIELD_NUMBER: _builtins.int
    RECV_TIME_NS_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    topic: _builtins.str
    """concrete key the message arrived on"""
    recv_time_ns: _builtins.int
    """flight-clock (wall) time of arrival"""
    payload: _builtins.bytes
    """the serialized message, byte-exact"""
    def __init__(
        self,
        *,
        topic: _builtins.str = ...,
        recv_time_ns: _builtins.int = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "recv_time_ns", b"recv_time_ns", "topic", b"topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RecordedSample: _TypeAlias = RecordedSample  # noqa: Y015
