"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Artifact uplink — the C1 deployment path, as wire contracts.

A new model, a new component, or a new configuration reaches the
spacecraft as ordinary bus messages that happen to arrive over RF:
one manifest, then chunks, then (separately, later, and only by
ground authority) an activation command. Nothing here executes
anything — the receiver STAGES bytes and verifies them; activation
switches a slot pointer; the consumer picks the new slot up when it
next starts. Trust is earned by measurement, so the sequence is
deliberately three commands, not one.
"""

from collections import abc as _abc
from flatsat.msgs import hal_pb2 as _hal_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ArtifactKind:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ArtifactKindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ArtifactKind.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ARTIFACT_KIND_UNSPECIFIED: _ArtifactKind.ValueType  # 0
    ARTIFACT_KIND_CONFIG: _ArtifactKind.ValueType  # 1
    """Tier 3: a .txtpb parameter set"""
    ARTIFACT_KIND_COMPONENT: _ArtifactKind.ValueType  # 2
    """Tier 2: an installable component"""
    ARTIFACT_KIND_MODEL: _ArtifactKind.ValueType  # 3
    """Tier 2: ML weights + feature spec"""

class ArtifactKind(_ArtifactKind, metaclass=_ArtifactKindEnumTypeWrapper):
    """What an artifact is and how to know it arrived intact."""

ARTIFACT_KIND_UNSPECIFIED: ArtifactKind.ValueType  # 0
ARTIFACT_KIND_CONFIG: ArtifactKind.ValueType  # 1
"""Tier 3: a .txtpb parameter set"""
ARTIFACT_KIND_COMPONENT: ArtifactKind.ValueType  # 2
"""Tier 2: an installable component"""
ARTIFACT_KIND_MODEL: ArtifactKind.ValueType  # 3
"""Tier 2: ML weights + feature spec"""
Global___ArtifactKind: _TypeAlias = ArtifactKind  # noqa: Y015

@_typing.final
class ArtifactManifest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    SIZE_BYTES_FIELD_NUMBER: _builtins.int
    SHA256_FIELD_NUMBER: _builtins.int
    CHUNK_COUNT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """logical artifact name, e.g. "ml_policy" """
    version: _builtins.str
    """uplinked version, e.g. "2026-07-28a" """
    kind: Global___ArtifactKind.ValueType
    size_bytes: _builtins.int
    sha256: _builtins.str
    """hex digest of the complete artifact"""
    chunk_count: _builtins.int
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        name: _builtins.str = ...,
        version: _builtins.str = ...,
        kind: Global___ArtifactKind.ValueType = ...,
        size_bytes: _builtins.int = ...,
        sha256: _builtins.str = ...,
        chunk_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_count", b"chunk_count", "header", b"header", "kind", b"kind", "name", b"name", "sha256", b"sha256", "size_bytes", b"size_bytes", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArtifactManifest: _TypeAlias = ArtifactManifest  # noqa: Y015

@_typing.final
class ArtifactChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    version: _builtins.str
    index: _builtins.int
    data: _builtins.bytes
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        name: _builtins.str = ...,
        version: _builtins.str = ...,
        index: _builtins.int = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "header", b"header", "index", b"index", "name", b"name", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArtifactChunk: _TypeAlias = ArtifactChunk  # noqa: Y015

@_typing.final
class ArtifactControl(_message.Message):
    """Ground command over the artifact slots. Activation is gated:
    ground_authority is required, and the flight side additionally
    refuses while the system is Safe — you do not hot-swap components
    during a safing event. Rollback carries no such gate: reverting to
    the last known-good slot is a toward-safety action.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Action:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ActionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ArtifactControl._Action.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ACTION_UNSPECIFIED: ArtifactControl._Action.ValueType  # 0
        ACTION_ACTIVATE: ArtifactControl._Action.ValueType  # 1
        ACTION_ROLLBACK: ArtifactControl._Action.ValueType  # 2

    class Action(_Action, metaclass=_ActionEnumTypeWrapper): ...
    ACTION_UNSPECIFIED: ArtifactControl.Action.ValueType  # 0
    ACTION_ACTIVATE: ArtifactControl.Action.ValueType  # 1
    ACTION_ROLLBACK: ArtifactControl.Action.ValueType  # 2

    HEADER_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    GROUND_AUTHORITY_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    action: Global___ArtifactControl.Action.ValueType
    name: _builtins.str
    version: _builtins.str
    """activate: which staged version; rollback: ignored"""
    ground_authority: _builtins.bool
    reason: _builtins.str
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        action: Global___ArtifactControl.Action.ValueType = ...,
        name: _builtins.str = ...,
        version: _builtins.str = ...,
        ground_authority: _builtins.bool = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "ground_authority", b"ground_authority", "header", b"header", "name", b"name", "reason", b"reason", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArtifactControl: _TypeAlias = ArtifactControl  # noqa: Y015

@_typing.final
class ArtifactSlots(_message.Message):
    """Per-artifact slot state, persisted so a reboot knows what is live."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ACTIVE_VERSION_FIELD_NUMBER: _builtins.int
    PREVIOUS_VERSION_FIELD_NUMBER: _builtins.int
    ACTIVATED_TIME_NS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    active_version: _builtins.str
    """empty = nothing activated yet"""
    previous_version: _builtins.str
    """rollback target; empty = nothing to revert to"""
    activated_time_ns: _builtins.int
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        active_version: _builtins.str = ...,
        previous_version: _builtins.str = ...,
        activated_time_ns: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activated_time_ns", b"activated_time_ns", "active_version", b"active_version", "name", b"name", "previous_version", b"previous_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArtifactSlots: _TypeAlias = ArtifactSlots  # noqa: Y015

@_typing.final
class UplinkStatus(_message.Message):
    """Uplink service telemetry: what is staged, what is live, what failed."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    STAGED_FIELD_NUMBER: _builtins.int
    SLOTS_FIELD_NUMBER: _builtins.int
    RECEIVING_FIELD_NUMBER: _builtins.int
    REJECTED_CHECKSUM_FIELD_NUMBER: _builtins.int
    REFUSED_ACTIVATIONS_FIELD_NUMBER: _builtins.int
    receiving: _builtins.int
    """artifacts with chunks still arriving"""
    rejected_checksum: _builtins.int
    """completed transfers whose digest disagreed"""
    refused_activations: _builtins.int
    """activation attempts blocked by the gates"""
    @_builtins.property
    def header(self) -> _hal_pb2.Header: ...
    @_builtins.property
    def staged(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """"name@version" fully received and verified"""

    @_builtins.property
    def slots(self) -> _containers.RepeatedCompositeFieldContainer[Global___ArtifactSlots]: ...
    def __init__(
        self,
        *,
        header: _hal_pb2.Header | None = ...,
        staged: _abc.Iterable[_builtins.str] | None = ...,
        slots: _abc.Iterable[Global___ArtifactSlots] | None = ...,
        receiving: _builtins.int = ...,
        rejected_checksum: _builtins.int = ...,
        refused_activations: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "receiving", b"receiving", "refused_activations", b"refused_activations", "rejected_checksum", b"rejected_checksum", "slots", b"slots", "staged", b"staged"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UplinkStatus: _TypeAlias = UplinkStatus  # noqa: Y015
