# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/msgs/uplink.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/msgs/uplink.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flatsat.msgs import hal_pb2 as flatsat_dot_msgs_dot_hal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66latsat/msgs/uplink.proto\x12\nflatsat.v1\x1a\x16\x66latsat/msgs/hal.proto\"\xb6\x01\n\x10\x41rtifactManifest\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12&\n\x04kind\x18\x04 \x01(\x0e\x32\x18.flatsat.v1.ArtifactKind\x12\x12\n\nsize_bytes\x18\x05 \x01(\x04\x12\x0e\n\x06sha256\x18\x06 \x01(\t\x12\x13\n\x0b\x63hunk_count\x18\x07 \x01(\r\"o\n\rArtifactChunk\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\r\n\x05index\x18\x04 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"\xfe\x01\n\x0f\x41rtifactControl\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x32\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\".flatsat.v1.ArtifactControl.Action\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x18\n\x10ground_authority\x18\x05 \x01(\x08\x12\x0e\n\x06reason\x18\x06 \x01(\t\"J\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x41\x43TION_ACTIVATE\x10\x01\x12\x13\n\x0f\x41\x43TION_ROLLBACK\x10\x02\"j\n\rArtifactSlots\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x61\x63tive_version\x18\x02 \x01(\t\x12\x18\n\x10previous_version\x18\x03 \x01(\t\x12\x19\n\x11\x61\x63tivated_time_ns\x18\x04 \x01(\x06\"\xb7\x01\n\x0cUplinkStatus\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x0e\n\x06staged\x18\x02 \x03(\t\x12(\n\x05slots\x18\x03 \x03(\x0b\x32\x19.flatsat.v1.ArtifactSlots\x12\x11\n\treceiving\x18\x04 \x01(\x04\x12\x19\n\x11rejected_checksum\x18\x05 \x01(\x04\x12\x1b\n\x13refused_activations\x18\x06 \x01(\x04*}\n\x0c\x41rtifactKind\x12\x1d\n\x19\x41RTIFACT_KIND_UNSPECIFIED\x10\x00\x12\x18\n\x14\x41RTIFACT_KIND_CONFIG\x10\x01\x12\x1b\n\x17\x41RTIFACT_KIND_COMPONENT\x10\x02\x12\x17\n\x13\x41RTIFACT_KIND_MODEL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.msgs.uplink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTIFACTKIND']._serialized_start=914
  _globals['_ARTIFACTKIND']._serialized_end=1039
  _globals['_ARTIFACTMANIFEST']._serialized_start=66
  _globals['_ARTIFACTMANIFEST']._serialized_end=248
  _globals['_ARTIFACTCHUNK']._serialized_start=250
  _globals['_ARTIFACTCHUNK']._serialized_end=361
  _globals['_ARTIFACTCONTROL']._serialized_start=364
  _globals['_ARTIFACTCONTROL']._serialized_end=618
  _globals['_ARTIFACTCONTROL_ACTION']._serialized_start=544
  _globals['_ARTIFACTCONTROL_ACTION']._serialized_end=618
  _globals['_ARTIFACTSLOTS']._serialized_start=620
  _globals['_ARTIFACTSLOTS']._serialized_end=726
  _globals['_UPLINKSTATUS']._serialized_start=729
  _globals['_UPLINKSTATUS']._serialized_end=912
# @@protoc_insertion_point(module_scope)
