# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/telemetry/telemetry_config.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/telemetry/telemetry_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(flatsat/telemetry/telemetry_config.proto\x12\nflatsat.v1\"\xc7\x01\n\x0fTelemetryConfig\x12\x0e\n\x06topics\x18\x01 \x03(\t\x12\x12\n\noutput_dir\x18\x02 \x01(\t\x12\x1b\n\x0emax_file_bytes\x18\x03 \x01(\x04H\x00\x88\x01\x01\x12\x1b\n\x0erotate_every_s\x18\x04 \x01(\x01H\x01\x88\x01\x01\x12\x1c\n\x0fmax_total_bytes\x18\x05 \x01(\x04H\x02\x88\x01\x01\x42\x11\n\x0f_max_file_bytesB\x11\n\x0f_rotate_every_sB\x12\n\x10_max_total_bytesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.telemetry.telemetry_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYCONFIG']._serialized_start=57
  _globals['_TELEMETRYCONFIG']._serialized_end=256
# @@protoc_insertion_point(module_scope)
