"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Telemetry-recorder composition — the [telemetry] block of a vehicle file."""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TelemetryConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOPICS_FIELD_NUMBER: _builtins.int
    OUTPUT_DIR_FIELD_NUMBER: _builtins.int
    MAX_FILE_BYTES_FIELD_NUMBER: _builtins.int
    ROTATE_EVERY_S_FIELD_NUMBER: _builtins.int
    MAX_TOTAL_BYTES_FIELD_NUMBER: _builtins.int
    output_dir: _builtins.str
    """empty = ~/flatsat-telemetry"""
    max_file_bytes: _builtins.int
    """rotate beyond this size; absent = 64 MiB"""
    rotate_every_s: _builtins.float
    """or beyond this age; absent = 900"""
    max_total_bytes: _builtins.int
    """prune oldest beyond this; absent = 4 GiB"""
    @_builtins.property
    def topics(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Bus key expressions to archive. Empty = hal/**, adcs/**, health/**, sys/**."""

    def __init__(
        self,
        *,
        topics: _abc.Iterable[_builtins.str] | None = ...,
        output_dir: _builtins.str = ...,
        max_file_bytes: _builtins.int | None = ...,
        rotate_every_s: _builtins.float | None = ...,
        max_total_bytes: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_max_file_bytes", b"_max_file_bytes", "_max_total_bytes", b"_max_total_bytes", "_rotate_every_s", b"_rotate_every_s", "max_file_bytes", b"max_file_bytes", "max_total_bytes", b"max_total_bytes", "rotate_every_s", b"rotate_every_s"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_max_file_bytes", b"_max_file_bytes", "_max_total_bytes", b"_max_total_bytes", "_rotate_every_s", b"_rotate_every_s", "max_file_bytes", b"max_file_bytes", "max_total_bytes", b"max_total_bytes", "output_dir", b"output_dir", "rotate_every_s", b"rotate_every_s", "topics", b"topics"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__max_file_bytes: _TypeAlias = _typing.Literal["max_file_bytes"]  # noqa: Y015
    _WhichOneofArgType__max_file_bytes: _TypeAlias = _typing.Literal["_max_file_bytes", b"_max_file_bytes"]  # noqa: Y015
    _WhichOneofReturnType__max_total_bytes: _TypeAlias = _typing.Literal["max_total_bytes"]  # noqa: Y015
    _WhichOneofArgType__max_total_bytes: _TypeAlias = _typing.Literal["_max_total_bytes", b"_max_total_bytes"]  # noqa: Y015
    _WhichOneofReturnType__rotate_every_s: _TypeAlias = _typing.Literal["rotate_every_s"]  # noqa: Y015
    _WhichOneofArgType__rotate_every_s: _TypeAlias = _typing.Literal["_rotate_every_s", b"_rotate_every_s"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_file_bytes) -> _WhichOneofReturnType__max_file_bytes | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_total_bytes) -> _WhichOneofReturnType__max_total_bytes | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__rotate_every_s) -> _WhichOneofReturnType__rotate_every_s | None: ...

Global___TelemetryConfig: _TypeAlias = TelemetryConfig  # noqa: Y015
