"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Per-driver configuration options — one message per registered driver.

The vehicle file selects a driver by filling exactly one of these
inside a SensorConfig/ActuatorConfig oneof (vehicle.proto); the oneof
field name IS the registry key, so the selector and its options can
never disagree. A new driver adds its message here and a oneof entry
there — the loaders never change.

`optional` marks numeric fields whose absence must be distinguishable
from zero (a default applies when absent; zero is a real value).
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class JetsonThermalOptions(_message.Message):
    """jetson_thermal: one kernel thermal zone as a temperature sensor."""

    DESCRIPTOR: _descriptor.Descriptor

    ZONE_FIELD_NUMBER: _builtins.int
    zone: _builtins.str
    """kernel zone type name, e.g. "tj-thermal" (required)"""
    def __init__(
        self,
        *,
        zone: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["zone", b"zone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JetsonThermalOptions: _TypeAlias = JetsonThermalOptions  # noqa: Y015

@_typing.final
class BasiliskImuOptions(_message.Message):
    """basilisk_imu: the sim bridge's truth stream through the device model."""

    DESCRIPTOR: _descriptor.Descriptor

    SPEC_FIELD_NUMBER: _builtins.int
    TRUTH_TOPIC_FIELD_NUMBER: _builtins.int
    STALE_AFTER_S_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    spec: _builtins.str
    """device file; empty = config/devices/imu0.txtpb"""
    truth_topic: _builtins.str
    """empty = sim/truth/state"""
    stale_after_s: _builtins.float
    """absent = 0.5"""
    seed: _builtins.int
    """corruption RNG seed; absent = unseeded"""
    def __init__(
        self,
        *,
        spec: _builtins.str = ...,
        truth_topic: _builtins.str = ...,
        stale_after_s: _builtins.float | None = ...,
        seed: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_seed", b"_seed", "_stale_after_s", b"_stale_after_s", "seed", b"seed", "stale_after_s", b"stale_after_s"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_seed", b"_seed", "_stale_after_s", b"_stale_after_s", "seed", b"seed", "spec", b"spec", "stale_after_s", b"stale_after_s", "truth_topic", b"truth_topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__seed: _TypeAlias = _typing.Literal["seed"]  # noqa: Y015
    _WhichOneofArgType__seed: _TypeAlias = _typing.Literal["_seed", b"_seed"]  # noqa: Y015
    _WhichOneofReturnType__stale_after_s: _TypeAlias = _typing.Literal["stale_after_s"]  # noqa: Y015
    _WhichOneofArgType__stale_after_s: _TypeAlias = _typing.Literal["_stale_after_s", b"_stale_after_s"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__seed) -> _WhichOneofReturnType__seed | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__stale_after_s) -> _WhichOneofReturnType__stale_after_s | None: ...

Global___BasiliskImuOptions: _TypeAlias = BasiliskImuOptions  # noqa: Y015

@_typing.final
class SimReactionWheelOptions(_message.Message):
    """sim_reaction_wheel: local wheel fake, no physics feedback."""

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_FIELD_NUMBER: _builtins.int
    device: _builtins.str
    """wheel device file, e.g. config/devices/wheel0.txtpb (required)"""
    def __init__(
        self,
        *,
        device: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SimReactionWheelOptions: _TypeAlias = SimReactionWheelOptions  # noqa: Y015

@_typing.final
class BasiliskReactionWheelOptions(_message.Message):
    """basilisk_reaction_wheel: wheel fake whose applied torque feeds the sim."""

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_FIELD_NUMBER: _builtins.int
    device: _builtins.str
    """wheel device file (required)"""
    def __init__(
        self,
        *,
        device: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BasiliskReactionWheelOptions: _TypeAlias = BasiliskReactionWheelOptions  # noqa: Y015
