"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Per-implementation options for the control composition — strategies,
guidance sources, and estimators. Selected via oneofs in
vehicle.proto's ControlConfig; each oneof field name IS the registry
key.

`optional` marks fields whose absence must be detected: gains have no
sensible zero, so a missing gain fails loudly at startup instead of
silently flying with 0.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RateDampingOptions(_message.Message):
    """rate_damping: PD on body-rate error — the detumble law."""

    DESCRIPTOR: _descriptor.Descriptor

    KP_FIELD_NUMBER: _builtins.int
    KD_FIELD_NUMBER: _builtins.int
    MAX_TORQUE_N_M_FIELD_NUMBER: _builtins.int
    kp: _builtins.float
    """required; N·m / (rad/s)"""
    kd: _builtins.float
    """required; N·m / (rad/s²)"""
    max_torque_n_m: _builtins.float
    """actuator envelope; absent = 1.0"""
    def __init__(
        self,
        *,
        kp: _builtins.float | None = ...,
        kd: _builtins.float | None = ...,
        max_torque_n_m: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_kd", b"_kd", "_kp", b"_kp", "_max_torque_n_m", b"_max_torque_n_m", "kd", b"kd", "kp", b"kp", "max_torque_n_m", b"max_torque_n_m"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_kd", b"_kd", "_kp", b"_kp", "_max_torque_n_m", b"_max_torque_n_m", "kd", b"kd", "kp", b"kp", "max_torque_n_m", b"max_torque_n_m"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__kd: _TypeAlias = _typing.Literal["kd"]  # noqa: Y015
    _WhichOneofArgType__kd: _TypeAlias = _typing.Literal["_kd", b"_kd"]  # noqa: Y015
    _WhichOneofReturnType__kp: _TypeAlias = _typing.Literal["kp"]  # noqa: Y015
    _WhichOneofArgType__kp: _TypeAlias = _typing.Literal["_kp", b"_kp"]  # noqa: Y015
    _WhichOneofReturnType__max_torque_n_m: _TypeAlias = _typing.Literal["max_torque_n_m"]  # noqa: Y015
    _WhichOneofArgType__max_torque_n_m: _TypeAlias = _typing.Literal["_max_torque_n_m", b"_max_torque_n_m"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__kd) -> _WhichOneofReturnType__kd | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__kp) -> _WhichOneofReturnType__kp | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_torque_n_m) -> _WhichOneofReturnType__max_torque_n_m | None: ...

Global___RateDampingOptions: _TypeAlias = RateDampingOptions  # noqa: Y015

@_typing.final
class PidOptions(_message.Message):
    """pid: PD plus integral action with anti-windup."""

    DESCRIPTOR: _descriptor.Descriptor

    KP_FIELD_NUMBER: _builtins.int
    KI_FIELD_NUMBER: _builtins.int
    KD_FIELD_NUMBER: _builtins.int
    INTEGRAL_LIMIT_FIELD_NUMBER: _builtins.int
    MAX_TORQUE_N_M_FIELD_NUMBER: _builtins.int
    kp: _builtins.float
    """required"""
    ki: _builtins.float
    """required"""
    kd: _builtins.float
    """required"""
    integral_limit: _builtins.float
    """per-axis clamp; absent = 1.0"""
    max_torque_n_m: _builtins.float
    """actuator envelope; absent = 1.0"""
    def __init__(
        self,
        *,
        kp: _builtins.float | None = ...,
        ki: _builtins.float | None = ...,
        kd: _builtins.float | None = ...,
        integral_limit: _builtins.float | None = ...,
        max_torque_n_m: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_integral_limit", b"_integral_limit", "_kd", b"_kd", "_ki", b"_ki", "_kp", b"_kp", "_max_torque_n_m", b"_max_torque_n_m", "integral_limit", b"integral_limit", "kd", b"kd", "ki", b"ki", "kp", b"kp", "max_torque_n_m", b"max_torque_n_m"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_integral_limit", b"_integral_limit", "_kd", b"_kd", "_ki", b"_ki", "_kp", b"_kp", "_max_torque_n_m", b"_max_torque_n_m", "integral_limit", b"integral_limit", "kd", b"kd", "ki", b"ki", "kp", b"kp", "max_torque_n_m", b"max_torque_n_m"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__integral_limit: _TypeAlias = _typing.Literal["integral_limit"]  # noqa: Y015
    _WhichOneofArgType__integral_limit: _TypeAlias = _typing.Literal["_integral_limit", b"_integral_limit"]  # noqa: Y015
    _WhichOneofReturnType__kd: _TypeAlias = _typing.Literal["kd"]  # noqa: Y015
    _WhichOneofArgType__kd: _TypeAlias = _typing.Literal["_kd", b"_kd"]  # noqa: Y015
    _WhichOneofReturnType__ki: _TypeAlias = _typing.Literal["ki"]  # noqa: Y015
    _WhichOneofArgType__ki: _TypeAlias = _typing.Literal["_ki", b"_ki"]  # noqa: Y015
    _WhichOneofReturnType__kp: _TypeAlias = _typing.Literal["kp"]  # noqa: Y015
    _WhichOneofArgType__kp: _TypeAlias = _typing.Literal["_kp", b"_kp"]  # noqa: Y015
    _WhichOneofReturnType__max_torque_n_m: _TypeAlias = _typing.Literal["max_torque_n_m"]  # noqa: Y015
    _WhichOneofArgType__max_torque_n_m: _TypeAlias = _typing.Literal["_max_torque_n_m", b"_max_torque_n_m"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__integral_limit) -> _WhichOneofReturnType__integral_limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__kd) -> _WhichOneofReturnType__kd | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ki) -> _WhichOneofReturnType__ki | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__kp) -> _WhichOneofReturnType__kp | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_torque_n_m) -> _WhichOneofReturnType__max_torque_n_m | None: ...

Global___PidOptions: _TypeAlias = PidOptions  # noqa: Y015

@_typing.final
class BdotOptions(_message.Message):
    """bdot: magnetic detumble — dipole m = -k·dB/dt from the magnetometer
    alone; no rate gyro, no attitude knowledge. Underactuated by physics:
    there is never torque about the field line, and convergence relies on
    the field ROTATING along the orbit, so the along-B rate component
    decays only at orbital tempo.
    """

    DESCRIPTOR: _descriptor.Descriptor

    GAIN_FIELD_NUMBER: _builtins.int
    MAX_DIPOLE_A_M2_FIELD_NUMBER: _builtins.int
    FILTER_TAU_S_FIELD_NUMBER: _builtins.int
    gain: _builtins.float
    """required; A·m² per (T/s)"""
    max_dipole_a_m2: _builtins.float
    """command envelope; absent = 1.0"""
    filter_tau_s: _builtins.float
    """dB/dt low-pass time constant; absent = 0.5"""
    def __init__(
        self,
        *,
        gain: _builtins.float | None = ...,
        max_dipole_a_m2: _builtins.float | None = ...,
        filter_tau_s: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_filter_tau_s", b"_filter_tau_s", "_gain", b"_gain", "_max_dipole_a_m2", b"_max_dipole_a_m2", "filter_tau_s", b"filter_tau_s", "gain", b"gain", "max_dipole_a_m2", b"max_dipole_a_m2"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_filter_tau_s", b"_filter_tau_s", "_gain", b"_gain", "_max_dipole_a_m2", b"_max_dipole_a_m2", "filter_tau_s", b"filter_tau_s", "gain", b"gain", "max_dipole_a_m2", b"max_dipole_a_m2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__filter_tau_s: _TypeAlias = _typing.Literal["filter_tau_s"]  # noqa: Y015
    _WhichOneofArgType__filter_tau_s: _TypeAlias = _typing.Literal["_filter_tau_s", b"_filter_tau_s"]  # noqa: Y015
    _WhichOneofReturnType__gain: _TypeAlias = _typing.Literal["gain"]  # noqa: Y015
    _WhichOneofArgType__gain: _TypeAlias = _typing.Literal["_gain", b"_gain"]  # noqa: Y015
    _WhichOneofReturnType__max_dipole_a_m2: _TypeAlias = _typing.Literal["max_dipole_a_m2"]  # noqa: Y015
    _WhichOneofArgType__max_dipole_a_m2: _TypeAlias = _typing.Literal["_max_dipole_a_m2", b"_max_dipole_a_m2"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__filter_tau_s) -> _WhichOneofReturnType__filter_tau_s | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__gain) -> _WhichOneofReturnType__gain | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_dipole_a_m2) -> _WhichOneofReturnType__max_dipole_a_m2 | None: ...

Global___BdotOptions: _TypeAlias = BdotOptions  # noqa: Y015

@_typing.final
class MomentumDumpOptions(_message.Message):
    """momentum_dump: the combined wheels + torquers system. Wheels fly the
    attitude (PD on rate error, identical to rate_damping); magnetorquers
    bleed the momentum the wheels have absorbed: m = dump_gain·(h x B)/|B|²
    produces external torque -k·h_perp, the attitude loop counters it, and
    the wheels hand their momentum to the field. The component of h along
    B waits for the orbit to rotate the field — the same underactuation
    floor B-dot has, now applied to stored momentum instead of body rate.
    """

    DESCRIPTOR: _descriptor.Descriptor

    KP_FIELD_NUMBER: _builtins.int
    KD_FIELD_NUMBER: _builtins.int
    MAX_TORQUE_N_M_FIELD_NUMBER: _builtins.int
    DUMP_GAIN_FIELD_NUMBER: _builtins.int
    MAX_DIPOLE_A_M2_FIELD_NUMBER: _builtins.int
    kp: _builtins.float
    """required; N·m / (rad/s)"""
    kd: _builtins.float
    """required; N·m / (rad/s²)"""
    max_torque_n_m: _builtins.float
    """wheel envelope; absent = 1.0"""
    dump_gain: _builtins.float
    """required; dipole per unit (h x B)/|B|²"""
    max_dipole_a_m2: _builtins.float
    """rod envelope; absent = 1.0"""
    def __init__(
        self,
        *,
        kp: _builtins.float | None = ...,
        kd: _builtins.float | None = ...,
        max_torque_n_m: _builtins.float | None = ...,
        dump_gain: _builtins.float | None = ...,
        max_dipole_a_m2: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_dump_gain", b"_dump_gain", "_kd", b"_kd", "_kp", b"_kp", "_max_dipole_a_m2", b"_max_dipole_a_m2", "_max_torque_n_m", b"_max_torque_n_m", "dump_gain", b"dump_gain", "kd", b"kd", "kp", b"kp", "max_dipole_a_m2", b"max_dipole_a_m2", "max_torque_n_m", b"max_torque_n_m"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_dump_gain", b"_dump_gain", "_kd", b"_kd", "_kp", b"_kp", "_max_dipole_a_m2", b"_max_dipole_a_m2", "_max_torque_n_m", b"_max_torque_n_m", "dump_gain", b"dump_gain", "kd", b"kd", "kp", b"kp", "max_dipole_a_m2", b"max_dipole_a_m2", "max_torque_n_m", b"max_torque_n_m"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__dump_gain: _TypeAlias = _typing.Literal["dump_gain"]  # noqa: Y015
    _WhichOneofArgType__dump_gain: _TypeAlias = _typing.Literal["_dump_gain", b"_dump_gain"]  # noqa: Y015
    _WhichOneofReturnType__kd: _TypeAlias = _typing.Literal["kd"]  # noqa: Y015
    _WhichOneofArgType__kd: _TypeAlias = _typing.Literal["_kd", b"_kd"]  # noqa: Y015
    _WhichOneofReturnType__kp: _TypeAlias = _typing.Literal["kp"]  # noqa: Y015
    _WhichOneofArgType__kp: _TypeAlias = _typing.Literal["_kp", b"_kp"]  # noqa: Y015
    _WhichOneofReturnType__max_dipole_a_m2: _TypeAlias = _typing.Literal["max_dipole_a_m2"]  # noqa: Y015
    _WhichOneofArgType__max_dipole_a_m2: _TypeAlias = _typing.Literal["_max_dipole_a_m2", b"_max_dipole_a_m2"]  # noqa: Y015
    _WhichOneofReturnType__max_torque_n_m: _TypeAlias = _typing.Literal["max_torque_n_m"]  # noqa: Y015
    _WhichOneofArgType__max_torque_n_m: _TypeAlias = _typing.Literal["_max_torque_n_m", b"_max_torque_n_m"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__dump_gain) -> _WhichOneofReturnType__dump_gain | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__kd) -> _WhichOneofReturnType__kd | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__kp) -> _WhichOneofReturnType__kp | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_dipole_a_m2) -> _WhichOneofReturnType__max_dipole_a_m2 | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_torque_n_m) -> _WhichOneofReturnType__max_torque_n_m | None: ...

Global___MomentumDumpOptions: _TypeAlias = MomentumDumpOptions  # noqa: Y015

@_typing.final
class ConstantRateOptions(_message.Message):
    """constant_rate: fixed body-rate target; all zeros (or empty) = detumble."""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_RATES_RAD_S_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def target_rates_rad_s(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """3 values, or empty for detumble"""

    def __init__(
        self,
        *,
        target_rates_rad_s: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["target_rates_rad_s", b"target_rates_rad_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConstantRateOptions: _TypeAlias = ConstantRateOptions  # noqa: Y015

@_typing.final
class PassthroughOptions(_message.Message):
    """passthrough: the measurement IS the estimate — nothing to configure."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PassthroughOptions: _TypeAlias = PassthroughOptions  # noqa: Y015

@_typing.final
class TriadOptions(_message.Message):
    """triad: deterministic two-vector attitude (TRIAD) from the magnetometer
    and sun sensor, against the ONBOARD models in flatsat/sim/orbit.py —
    the same pure-python models the plants fly, which is what makes the
    estimate testable everywhere. Attitude is invalid in eclipse (one
    vector is not an attitude); rates still pass through from the gyro.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ORBIT_FIELD_NUMBER: _builtins.int
    orbit: _builtins.str
    """saved orbit file the onboard models propagate (required)"""
    def __init__(
        self,
        *,
        orbit: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["orbit", b"orbit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TriadOptions: _TypeAlias = TriadOptions  # noqa: Y015

@_typing.final
class SunPointOptions(_message.Message):
    """sun_point: the flagship pointing law. Wheels align a body axis with
    the MEASURED sun vector (alignment + rate damping); magnetorquers keep
    dumping wheel momentum, exactly the momentum_dump law. In eclipse the
    alignment term pauses — rate damping and the dump carry through.
    """

    DESCRIPTOR: _descriptor.Descriptor

    POINT_AXIS_FIELD_NUMBER: _builtins.int
    K_ALIGN_FIELD_NUMBER: _builtins.int
    KP_FIELD_NUMBER: _builtins.int
    KD_FIELD_NUMBER: _builtins.int
    MAX_TORQUE_N_M_FIELD_NUMBER: _builtins.int
    DUMP_GAIN_FIELD_NUMBER: _builtins.int
    MAX_DIPOLE_A_M2_FIELD_NUMBER: _builtins.int
    k_align: _builtins.float
    """alignment gain [N·m per rad-ish]; required"""
    kp: _builtins.float
    """required; rate damping N·m / (rad/s)"""
    kd: _builtins.float
    """required; N·m / (rad/s²)"""
    max_torque_n_m: _builtins.float
    """wheel envelope; absent = 1.0"""
    dump_gain: _builtins.float
    """required; dipole per unit (h x B)/|B|²"""
    max_dipole_a_m2: _builtins.float
    """rod envelope; absent = 1.0"""
    @_builtins.property
    def point_axis(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """body axis to aim at the sun; 3 values (required)"""

    def __init__(
        self,
        *,
        point_axis: _abc.Iterable[_builtins.float] | None = ...,
        k_align: _builtins.float | None = ...,
        kp: _builtins.float | None = ...,
        kd: _builtins.float | None = ...,
        max_torque_n_m: _builtins.float | None = ...,
        dump_gain: _builtins.float | None = ...,
        max_dipole_a_m2: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_dump_gain", b"_dump_gain", "_k_align", b"_k_align", "_kd", b"_kd", "_kp", b"_kp", "_max_dipole_a_m2", b"_max_dipole_a_m2", "_max_torque_n_m", b"_max_torque_n_m", "dump_gain", b"dump_gain", "k_align", b"k_align", "kd", b"kd", "kp", b"kp", "max_dipole_a_m2", b"max_dipole_a_m2", "max_torque_n_m", b"max_torque_n_m"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_dump_gain", b"_dump_gain", "_k_align", b"_k_align", "_kd", b"_kd", "_kp", b"_kp", "_max_dipole_a_m2", b"_max_dipole_a_m2", "_max_torque_n_m", b"_max_torque_n_m", "dump_gain", b"dump_gain", "k_align", b"k_align", "kd", b"kd", "kp", b"kp", "max_dipole_a_m2", b"max_dipole_a_m2", "max_torque_n_m", b"max_torque_n_m", "point_axis", b"point_axis"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__dump_gain: _TypeAlias = _typing.Literal["dump_gain"]  # noqa: Y015
    _WhichOneofArgType__dump_gain: _TypeAlias = _typing.Literal["_dump_gain", b"_dump_gain"]  # noqa: Y015
    _WhichOneofReturnType__k_align: _TypeAlias = _typing.Literal["k_align"]  # noqa: Y015
    _WhichOneofArgType__k_align: _TypeAlias = _typing.Literal["_k_align", b"_k_align"]  # noqa: Y015
    _WhichOneofReturnType__kd: _TypeAlias = _typing.Literal["kd"]  # noqa: Y015
    _WhichOneofArgType__kd: _TypeAlias = _typing.Literal["_kd", b"_kd"]  # noqa: Y015
    _WhichOneofReturnType__kp: _TypeAlias = _typing.Literal["kp"]  # noqa: Y015
    _WhichOneofArgType__kp: _TypeAlias = _typing.Literal["_kp", b"_kp"]  # noqa: Y015
    _WhichOneofReturnType__max_dipole_a_m2: _TypeAlias = _typing.Literal["max_dipole_a_m2"]  # noqa: Y015
    _WhichOneofArgType__max_dipole_a_m2: _TypeAlias = _typing.Literal["_max_dipole_a_m2", b"_max_dipole_a_m2"]  # noqa: Y015
    _WhichOneofReturnType__max_torque_n_m: _TypeAlias = _typing.Literal["max_torque_n_m"]  # noqa: Y015
    _WhichOneofArgType__max_torque_n_m: _TypeAlias = _typing.Literal["_max_torque_n_m", b"_max_torque_n_m"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__dump_gain) -> _WhichOneofReturnType__dump_gain | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__k_align) -> _WhichOneofReturnType__k_align | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__kd) -> _WhichOneofReturnType__kd | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__kp) -> _WhichOneofReturnType__kp | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_dipole_a_m2) -> _WhichOneofReturnType__max_dipole_a_m2 | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_torque_n_m) -> _WhichOneofReturnType__max_torque_n_m | None: ...

Global___SunPointOptions: _TypeAlias = SunPointOptions  # noqa: Y015
