"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Device-intrinsic truth — the datasheet a config/devices/*.txtpb file
fills out. True of the unit no matter which spacecraft it is bolted
to; where a device POINTS is integration truth (vehicle.proto
MountingConfig), never here.

Calibration fields (measured scale factors, biases, alignment) land
here when a characterization campaign first produces them —
discovered knowledge updates the data file, never the design.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ImuDevice(_message.Message):
    """IMU: limits, resolution, and noise character. Read by BOTH the
    flight-side driver (to know the device) and the simulation's sensor
    model (to corrupt truth the way the device would).
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    GYRO_NOISE_RAD_S_FIELD_NUMBER: _builtins.int
    GYRO_FULL_SCALE_RAD_S_FIELD_NUMBER: _builtins.int
    GYRO_LSB_RAD_S_FIELD_NUMBER: _builtins.int
    ACCEL_NOISE_M_S2_FIELD_NUMBER: _builtins.int
    ACCEL_FULL_SCALE_M_S2_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """instance name (becomes the message source)"""
    rate_hz: _builtins.float
    """native output data rate"""
    gyro_noise_rad_s: _builtins.float
    """white-noise sigma per gyro axis"""
    gyro_full_scale_rad_s: _builtins.float
    """measurement limit; beyond it the device rails"""
    gyro_lsb_rad_s: _builtins.float
    """quantization step of the gyro output"""
    accel_noise_m_s2: _builtins.float
    """white-noise sigma per accelerometer axis"""
    accel_full_scale_m_s2: _builtins.float
    """accelerometer measurement limit"""
    temperature_c: _builtins.float
    """nominal reported die temperature"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        gyro_noise_rad_s: _builtins.float = ...,
        gyro_full_scale_rad_s: _builtins.float = ...,
        gyro_lsb_rad_s: _builtins.float = ...,
        accel_noise_m_s2: _builtins.float = ...,
        accel_full_scale_m_s2: _builtins.float = ...,
        temperature_c: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accel_full_scale_m_s2", b"accel_full_scale_m_s2", "accel_noise_m_s2", b"accel_noise_m_s2", "gyro_full_scale_rad_s", b"gyro_full_scale_rad_s", "gyro_lsb_rad_s", b"gyro_lsb_rad_s", "gyro_noise_rad_s", b"gyro_noise_rad_s", "name", b"name", "rate_hz", b"rate_hz", "temperature_c", b"temperature_c"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ImuDevice: _TypeAlias = ImuDevice  # noqa: Y015

@_typing.final
class WheelDevice(_message.Message):
    """Reaction wheel: torque and momentum envelopes."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    MAX_TORQUE_N_M_FIELD_NUMBER: _builtins.int
    MAX_MOMENTUM_N_M_S_FIELD_NUMBER: _builtins.int
    ROTOR_INERTIA_KG_M2_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """instance name (becomes the message source)"""
    max_torque_n_m: _builtins.float
    """torque envelope; commands clip (and flag) beyond"""
    max_momentum_n_m_s: _builtins.float
    """momentum storage; SATURATED at the rail"""
    rotor_inertia_kg_m2: _builtins.float
    """speed = momentum / inertia"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        max_torque_n_m: _builtins.float = ...,
        max_momentum_n_m_s: _builtins.float = ...,
        rotor_inertia_kg_m2: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_momentum_n_m_s", b"max_momentum_n_m_s", "max_torque_n_m", b"max_torque_n_m", "name", b"name", "rotor_inertia_kg_m2", b"rotor_inertia_kg_m2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WheelDevice: _TypeAlias = WheelDevice  # noqa: Y015
