# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/hardware/devices.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/hardware/devices.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66latsat/hardware/devices.proto\x12\nflatsat.v1\"\xa9\x02\n\tImuDevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07rate_hz\x18\x02 \x01(\x01\x12\x18\n\x10gyro_noise_rad_s\x18\x03 \x01(\x01\x12\x1d\n\x15gyro_full_scale_rad_s\x18\x04 \x01(\x01\x12\x16\n\x0egyro_lsb_rad_s\x18\x05 \x01(\x01\x12\x18\n\x10\x61\x63\x63\x65l_noise_m_s2\x18\x06 \x01(\x01\x12\x1d\n\x15\x61\x63\x63\x65l_full_scale_m_s2\x18\x07 \x01(\x01\x12\x15\n\rtemperature_c\x18\x08 \x01(\x01\x12\x1c\n\x14temperature_sunlit_c\x18\t \x01(\x01\x12\x1d\n\x15temperature_eclipse_c\x18\n \x01(\x01\x12\x1f\n\x17thermal_time_constant_s\x18\x0b \x01(\x01\"l\n\x0bWheelDevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0emax_torque_n_m\x18\x02 \x01(\x01\x12\x1a\n\x12max_momentum_n_m_s\x18\x03 \x01(\x01\x12\x1b\n\x13rotor_inertia_kg_m2\x18\x04 \x01(\x01\";\n\x12MagnetorquerDevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0fmax_dipole_a_m2\x18\x02 \x01(\x01\"C\n\x0fSunSensorDevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07rate_hz\x18\x02 \x01(\x01\x12\x11\n\tnoise_rad\x18\x03 \x01(\x01\"i\n\x12MagnetometerDevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07rate_hz\x18\x02 \x01(\x01\x12\x0f\n\x07noise_t\x18\x03 \x01(\x01\x12\x14\n\x0c\x66ull_scale_t\x18\x04 \x01(\x01\x12\r\n\x05lsb_t\x18\x05 \x01(\x01\"\xae\x01\n\x11StarTrackerDevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07rate_hz\x18\x02 \x01(\x01\x12\x17\n\x0f\x63ross_noise_rad\x18\x03 \x01(\x01\x12\x16\n\x0eroll_noise_rad\x18\x04 \x01(\x01\x12\x11\n\tboresight\x18\x05 \x03(\x01\x12\x19\n\x11sun_exclusion_deg\x18\x06 \x01(\x01\x12\x1b\n\x13\x65\x61rth_exclusion_deg\x18\x07 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.hardware.devices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMUDEVICE']._serialized_start=47
  _globals['_IMUDEVICE']._serialized_end=344
  _globals['_WHEELDEVICE']._serialized_start=346
  _globals['_WHEELDEVICE']._serialized_end=454
  _globals['_MAGNETORQUERDEVICE']._serialized_start=456
  _globals['_MAGNETORQUERDEVICE']._serialized_end=515
  _globals['_SUNSENSORDEVICE']._serialized_start=517
  _globals['_SUNSENSORDEVICE']._serialized_end=584
  _globals['_MAGNETOMETERDEVICE']._serialized_start=586
  _globals['_MAGNETOMETERDEVICE']._serialized_end=691
  _globals['_STARTRACKERDEVICE']._serialized_start=694
  _globals['_STARTRACKERDEVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
