"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Device-intrinsic truth — the datasheet a config/devices/*.txtpb file
fills out. True of the unit no matter which spacecraft it is bolted
to; where a device POINTS is integration truth (vehicle.proto
MountingConfig), never here.

Calibration fields (measured scale factors, biases, alignment) land
here when a characterization campaign first produces them —
discovered knowledge updates the data file, never the design.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ImuDevice(_message.Message):
    """IMU: limits, resolution, and noise character. Read by BOTH the
    flight-side driver (to know the device) and the simulation's sensor
    model (to corrupt truth the way the device would).
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    GYRO_NOISE_RAD_S_FIELD_NUMBER: _builtins.int
    GYRO_FULL_SCALE_RAD_S_FIELD_NUMBER: _builtins.int
    GYRO_LSB_RAD_S_FIELD_NUMBER: _builtins.int
    ACCEL_NOISE_M_S2_FIELD_NUMBER: _builtins.int
    ACCEL_FULL_SCALE_M_S2_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    TEMPERATURE_SUNLIT_C_FIELD_NUMBER: _builtins.int
    TEMPERATURE_ECLIPSE_C_FIELD_NUMBER: _builtins.int
    THERMAL_TIME_CONSTANT_S_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """instance name (becomes the message source)"""
    rate_hz: _builtins.float
    """native output data rate"""
    gyro_noise_rad_s: _builtins.float
    """white-noise sigma per gyro axis"""
    gyro_full_scale_rad_s: _builtins.float
    """measurement limit; beyond it the device rails"""
    gyro_lsb_rad_s: _builtins.float
    """quantization step of the gyro output"""
    accel_noise_m_s2: _builtins.float
    """white-noise sigma per accelerometer axis"""
    accel_full_scale_m_s2: _builtins.float
    """accelerometer measurement limit"""
    temperature_c: _builtins.float
    """nominal reported die temperature (also the initial value)"""
    temperature_sunlit_c: _builtins.float
    """Orbital thermal response — MODELED, not measured: the die relaxes
    first-order toward a sunlit or eclipse equilibrium as the vehicle
    crosses the terminator. Zero time constant = static temperature_c
    (the pre-thermal behavior, and the right choice for a bench part
    that never sees space).
    equilibrium in sunlight
    """
    temperature_eclipse_c: _builtins.float
    """equilibrium in shadow"""
    thermal_time_constant_s: _builtins.float
    """first-order lag; 0 disables the model"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        gyro_noise_rad_s: _builtins.float = ...,
        gyro_full_scale_rad_s: _builtins.float = ...,
        gyro_lsb_rad_s: _builtins.float = ...,
        accel_noise_m_s2: _builtins.float = ...,
        accel_full_scale_m_s2: _builtins.float = ...,
        temperature_c: _builtins.float = ...,
        temperature_sunlit_c: _builtins.float = ...,
        temperature_eclipse_c: _builtins.float = ...,
        thermal_time_constant_s: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accel_full_scale_m_s2", b"accel_full_scale_m_s2", "accel_noise_m_s2", b"accel_noise_m_s2", "gyro_full_scale_rad_s", b"gyro_full_scale_rad_s", "gyro_lsb_rad_s", b"gyro_lsb_rad_s", "gyro_noise_rad_s", b"gyro_noise_rad_s", "name", b"name", "rate_hz", b"rate_hz", "temperature_c", b"temperature_c", "temperature_eclipse_c", b"temperature_eclipse_c", "temperature_sunlit_c", b"temperature_sunlit_c", "thermal_time_constant_s", b"thermal_time_constant_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ImuDevice: _TypeAlias = ImuDevice  # noqa: Y015

@_typing.final
class WheelDevice(_message.Message):
    """Reaction wheel: torque and momentum envelopes."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    MAX_TORQUE_N_M_FIELD_NUMBER: _builtins.int
    MAX_MOMENTUM_N_M_S_FIELD_NUMBER: _builtins.int
    ROTOR_INERTIA_KG_M2_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """instance name (becomes the message source)"""
    max_torque_n_m: _builtins.float
    """torque envelope; commands clip (and flag) beyond"""
    max_momentum_n_m_s: _builtins.float
    """momentum storage; SATURATED at the rail"""
    rotor_inertia_kg_m2: _builtins.float
    """speed = momentum / inertia"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        max_torque_n_m: _builtins.float = ...,
        max_momentum_n_m_s: _builtins.float = ...,
        rotor_inertia_kg_m2: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_momentum_n_m_s", b"max_momentum_n_m_s", "max_torque_n_m", b"max_torque_n_m", "name", b"name", "rotor_inertia_kg_m2", b"rotor_inertia_kg_m2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WheelDevice: _TypeAlias = WheelDevice  # noqa: Y015

@_typing.final
class MagnetorquerDevice(_message.Message):
    """Magnetorquer rod: specified by DIPOLE MOMENT, deliberately NOT torque.
    Torque is m x B, computed by the plant from the local field, so the
    available torque varies continuously around the orbit and is always
    zero about the field line. A max_torque field here would grant
    authority the device does not have and make magnetic detumble look
    better than reality (docs/ARCHITECTURE.md, "A magnetorquer has no
    maximum torque").
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    MAX_DIPOLE_A_M2_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """instance name (becomes the message source)"""
    max_dipole_a_m2: _builtins.float
    """dipole envelope; commands clip (and flag) beyond"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        max_dipole_a_m2: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_dipole_a_m2", b"max_dipole_a_m2", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MagnetorquerDevice: _TypeAlias = MagnetorquerDevice  # noqa: Y015

@_typing.final
class SunSensorDevice(_message.Message):
    """Coarse sun sensor: reports the sun unit vector with angular noise,
    and reports DARKNESS honestly (sun_visible false) in eclipse — no
    measurement is a measurement of shadow, not a fault.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    NOISE_RAD_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """instance name (becomes the message source)"""
    rate_hz: _builtins.float
    """native output data rate"""
    noise_rad: _builtins.float
    """angular noise sigma on the sun direction"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        noise_rad: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "noise_rad", b"noise_rad", "rate_hz", b"rate_hz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SunSensorDevice: _TypeAlias = SunSensorDevice  # noqa: Y015

@_typing.final
class MagnetometerDevice(_message.Message):
    """Magnetometer: noise and range character. Read by BOTH the flight-side
    driver (to know the device) and the simulation's sensor model (to
    corrupt the truth field the way the device would).
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    NOISE_T_FIELD_NUMBER: _builtins.int
    FULL_SCALE_T_FIELD_NUMBER: _builtins.int
    LSB_T_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """instance name (becomes the message source)"""
    rate_hz: _builtins.float
    """native output data rate"""
    noise_t: _builtins.float
    """white-noise sigma per axis, tesla"""
    full_scale_t: _builtins.float
    """measurement limit; beyond it the device rails"""
    lsb_t: _builtins.float
    """quantization step of the output"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        noise_t: _builtins.float = ...,
        full_scale_t: _builtins.float = ...,
        lsb_t: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["full_scale_t", b"full_scale_t", "lsb_t", b"lsb_t", "name", b"name", "noise_t", b"noise_t", "rate_hz", b"rate_hz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MagnetometerDevice: _TypeAlias = MagnetometerDevice  # noqa: Y015
