"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
FDIR RULEBOOK SCHEMA — the fdir block of a vehicle file.

Fault detection is the same sense-decide-act shape as attitude
control, with the SYSTEM as the plant: these declarative rules are
the limit checker (sense), the arbiter decides, and the response
ladder actuates — restart is systemd's Restart= tier, reconfigure
arrives with the parameter database, and "request Safe" is FDIR
acting as a CLIENT of mode authority, never its owner.

Rules watch bus telemetry every process already publishes. The first
thresholds came from measured behavior: the 2026-07-28 HIL stall
census (39 stale episodes, median just over the 0.5 s staleness
threshold, 2.2% of the window) says brief stalls are NORMAL — only a
sustained ratio is a fault.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FlagRatioRule(_message.Message):
    """Condition: fraction of samples on a topic carrying any of the given
    validity flags exceeds max_ratio over a sliding window.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_FIELD_NUMBER: _builtins.int
    FLAG_MASK_FIELD_NUMBER: _builtins.int
    WINDOW_S_FIELD_NUMBER: _builtins.int
    MAX_RATIO_FIELD_NUMBER: _builtins.int
    topic: _builtins.str
    """bus key expression to watch"""
    flag_mask: _builtins.int
    """ValidityFlag bits that count as flagged (e.g. 8 = STALE)"""
    window_s: _builtins.float
    """sliding window length"""
    max_ratio: _builtins.float
    """flagged fraction beyond which the condition holds"""
    def __init__(
        self,
        *,
        topic: _builtins.str = ...,
        flag_mask: _builtins.int = ...,
        window_s: _builtins.float = ...,
        max_ratio: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flag_mask", b"flag_mask", "max_ratio", b"max_ratio", "topic", b"topic", "window_s", b"window_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FlagRatioRule: _TypeAlias = FlagRatioRule  # noqa: Y015

@_typing.final
class SilenceRule(_message.Message):
    """Condition: nothing at all on a topic for too long. Distinct from
    STALE by design — a daemon that flags is degraded; a daemon that
    goes silent is DEAD, a different fault with a different response.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_FIELD_NUMBER: _builtins.int
    TIMEOUT_S_FIELD_NUMBER: _builtins.int
    topic: _builtins.str
    timeout_s: _builtins.float
    def __init__(
        self,
        *,
        topic: _builtins.str = ...,
        timeout_s: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["timeout_s", b"timeout_s", "topic", b"topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SilenceRule: _TypeAlias = SilenceRule  # noqa: Y015

@_typing.final
class FdirRule(_message.Message):
    """One named rule: a check plus the anti-chatter persistence bound."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    MIN_TRIP_S_FIELD_NUMBER: _builtins.int
    FLAG_RATIO_FIELD_NUMBER: _builtins.int
    SILENCE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    min_trip_s: _builtins.float
    """condition must persist this long; absent = 1.0"""
    @_builtins.property
    def flag_ratio(self) -> Global___FlagRatioRule: ...
    @_builtins.property
    def silence(self) -> Global___SilenceRule: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        min_trip_s: _builtins.float | None = ...,
        flag_ratio: Global___FlagRatioRule | None = ...,
        silence: Global___SilenceRule | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_min_trip_s", b"_min_trip_s", "check", b"check", "flag_ratio", b"flag_ratio", "min_trip_s", b"min_trip_s", "silence", b"silence"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_min_trip_s", b"_min_trip_s", "check", b"check", "flag_ratio", b"flag_ratio", "min_trip_s", b"min_trip_s", "name", b"name", "silence", b"silence"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__min_trip_s: _TypeAlias = _typing.Literal["min_trip_s"]  # noqa: Y015
    _WhichOneofArgType__min_trip_s: _TypeAlias = _typing.Literal["_min_trip_s", b"_min_trip_s"]  # noqa: Y015
    _WhichOneofReturnType_check: _TypeAlias = _typing.Literal["flag_ratio", "silence"]  # noqa: Y015
    _WhichOneofArgType_check: _TypeAlias = _typing.Literal["check", b"check"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__min_trip_s) -> _WhichOneofReturnType__min_trip_s | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_check) -> _WhichOneofReturnType_check | None: ...

Global___FdirRule: _TypeAlias = FdirRule  # noqa: Y015

@_typing.final
class FdirConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rules(self) -> _containers.RepeatedCompositeFieldContainer[Global___FdirRule]: ...
    def __init__(
        self,
        *,
        rules: _abc.Iterable[Global___FdirRule] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rules", b"rules"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FdirConfig: _TypeAlias = FdirConfig  # noqa: Y015
