# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/control/health/fdir_config.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/control/health/fdir_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(flatsat/control/health/fdir_config.proto\x12\nflatsat.v1\"V\n\rFlagRatioRule\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\tflag_mask\x18\x02 \x01(\r\x12\x10\n\x08window_s\x18\x03 \x01(\x01\x12\x11\n\tmax_ratio\x18\x04 \x01(\x01\"/\n\x0bSilenceRule\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\ttimeout_s\x18\x02 \x01(\x01\"\xa6\x01\n\x08\x46\x64irRule\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\nmin_trip_s\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12/\n\nflag_ratio\x18\n \x01(\x0b\x32\x19.flatsat.v1.FlagRatioRuleH\x00\x12*\n\x07silence\x18\x0b \x01(\x0b\x32\x17.flatsat.v1.SilenceRuleH\x00\x42\x07\n\x05\x63heckB\r\n\x0b_min_trip_s\"1\n\nFdirConfig\x12#\n\x05rules\x18\x01 \x03(\x0b\x32\x14.flatsat.v1.FdirRuleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.control.health.fdir_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLAGRATIORULE']._serialized_start=56
  _globals['_FLAGRATIORULE']._serialized_end=142
  _globals['_SILENCERULE']._serialized_start=144
  _globals['_SILENCERULE']._serialized_end=191
  _globals['_FDIRRULE']._serialized_start=194
  _globals['_FDIRRULE']._serialized_end=360
  _globals['_FDIRCONFIG']._serialized_start=362
  _globals['_FDIRCONFIG']._serialized_end=411
# @@protoc_insertion_point(module_scope)
