"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
VEHICLE COMPOSITION SCHEMA — what a config/vehicles/*.txtpb file fills out.

A spacecraft is a config file: sensors, actuators, control strategy,
estimator, objective — plus the physical model ([body] + per-device
mounting). Implementations are selected by filling exactly one entry
of a oneof; the oneof FIELD NAME is the registry key
(flatsat/core/registry.py), so the selector and its typed options can
never disagree, and a misspelled field is a parse error, not a
silently ignored key.

Deployment concerns (RT priority, cores, memory) live in
deployment.toml; board topology in tools/host-profiles/. Same vehicle,
different flight computers.
"""

from collections import abc as _abc
from flatsat.comms import comms_config_pb2 as _comms_config_pb2
from flatsat.control.attitude import control_options_pb2 as _control_options_pb2
from flatsat.control.health import fdir_config_pb2 as _fdir_config_pb2
from flatsat.hardware.drivers import driver_options_pb2 as _driver_options_pb2
from flatsat.mode import mode_config_pb2 as _mode_config_pb2
from flatsat.telemetry import telemetry_config_pb2 as _telemetry_config_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MountingConfig(_message.Message):
    """Where and how a device sits in the body frame (integration truth)."""

    DESCRIPTOR: _descriptor.Descriptor

    POSITION_M_FIELD_NUMBER: _builtins.int
    AXIS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def position_m(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """3 values, body frame"""

    @_builtins.property
    def axis(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """3 values; normalized at load, zero vector fails"""

    def __init__(
        self,
        *,
        position_m: _abc.Iterable[_builtins.float] | None = ...,
        axis: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["axis", b"axis", "position_m", b"position_m"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MountingConfig: _TypeAlias = MountingConfig  # noqa: Y015

@_typing.final
class BodyConfig(_message.Message):
    """The vehicle's rigid-body physical model. Read by flight software AND
    by the sim bridge to build its plant — the same numbers, so sim and
    flight cannot disagree about the spacecraft by accident.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MASS_KG_FIELD_NUMBER: _builtins.int
    INERTIA_KG_M2_FIELD_NUMBER: _builtins.int
    mass_kg: _builtins.float
    @_builtins.property
    def inertia_kg_m2(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """3x3 tensor, row-major, 9 values"""

    def __init__(
        self,
        *,
        mass_kg: _builtins.float = ...,
        inertia_kg_m2: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["inertia_kg_m2", b"inertia_kg_m2", "mass_kg", b"mass_kg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BodyConfig: _TypeAlias = BodyConfig  # noqa: Y015

@_typing.final
class SensorConfig(_message.Message):
    """One sensor: identity + cadence + exactly one driver's options."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    JETSON_THERMAL_FIELD_NUMBER: _builtins.int
    BASILISK_IMU_FIELD_NUMBER: _builtins.int
    BASILISK_MAGNETOMETER_FIELD_NUMBER: _builtins.int
    BASILISK_SUN_SENSOR_FIELD_NUMBER: _builtins.int
    BASILISK_STAR_TRACKER_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """instance name; becomes the message source and unit name"""
    topic: _builtins.str
    """bus key the daemon publishes on"""
    rate_hz: _builtins.float
    """publish cadence"""
    @_builtins.property
    def jetson_thermal(self) -> _driver_options_pb2.JetsonThermalOptions: ...
    @_builtins.property
    def basilisk_imu(self) -> _driver_options_pb2.BasiliskImuOptions: ...
    @_builtins.property
    def basilisk_magnetometer(self) -> _driver_options_pb2.BasiliskMagnetometerOptions: ...
    @_builtins.property
    def basilisk_sun_sensor(self) -> _driver_options_pb2.BasiliskSunSensorOptions: ...
    @_builtins.property
    def basilisk_star_tracker(self) -> _driver_options_pb2.BasiliskStarTrackerOptions: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        topic: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        jetson_thermal: _driver_options_pb2.JetsonThermalOptions | None = ...,
        basilisk_imu: _driver_options_pb2.BasiliskImuOptions | None = ...,
        basilisk_magnetometer: _driver_options_pb2.BasiliskMagnetometerOptions | None = ...,
        basilisk_sun_sensor: _driver_options_pb2.BasiliskSunSensorOptions | None = ...,
        basilisk_star_tracker: _driver_options_pb2.BasiliskStarTrackerOptions | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["basilisk_imu", b"basilisk_imu", "basilisk_magnetometer", b"basilisk_magnetometer", "basilisk_star_tracker", b"basilisk_star_tracker", "basilisk_sun_sensor", b"basilisk_sun_sensor", "jetson_thermal", b"jetson_thermal", "options", b"options"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["basilisk_imu", b"basilisk_imu", "basilisk_magnetometer", b"basilisk_magnetometer", "basilisk_star_tracker", b"basilisk_star_tracker", "basilisk_sun_sensor", b"basilisk_sun_sensor", "jetson_thermal", b"jetson_thermal", "name", b"name", "options", b"options", "rate_hz", b"rate_hz", "topic", b"topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_options: _TypeAlias = _typing.Literal["jetson_thermal", "basilisk_imu", "basilisk_magnetometer", "basilisk_sun_sensor", "basilisk_star_tracker"]  # noqa: Y015
    _WhichOneofArgType_options: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_options) -> _WhichOneofReturnType_options | None: ...

Global___SensorConfig: _TypeAlias = SensorConfig  # noqa: Y015

@_typing.final
class ActuatorConfig(_message.Message):
    """One actuator: identity + topics + mounting + exactly one driver's options."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    COMMAND_TOPIC_FIELD_NUMBER: _builtins.int
    STATE_TOPIC_FIELD_NUMBER: _builtins.int
    RATE_HZ_FIELD_NUMBER: _builtins.int
    STALE_ZERO_S_FIELD_NUMBER: _builtins.int
    MOUNTING_FIELD_NUMBER: _builtins.int
    SIM_REACTION_WHEEL_FIELD_NUMBER: _builtins.int
    BASILISK_REACTION_WHEEL_FIELD_NUMBER: _builtins.int
    BASILISK_MAGNETORQUER_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    command_topic: _builtins.str
    """body-frame commands consumed from here"""
    state_topic: _builtins.str
    """device state published here"""
    rate_hz: _builtins.float
    """apply/publish cadence"""
    stale_zero_s: _builtins.float
    """command age beyond which the daemon applies ZERO"""
    @_builtins.property
    def mounting(self) -> Global___MountingConfig:
        """the daemon projects body commands through this"""

    @_builtins.property
    def sim_reaction_wheel(self) -> _driver_options_pb2.SimReactionWheelOptions: ...
    @_builtins.property
    def basilisk_reaction_wheel(self) -> _driver_options_pb2.BasiliskReactionWheelOptions: ...
    @_builtins.property
    def basilisk_magnetorquer(self) -> _driver_options_pb2.BasiliskMagnetorquerOptions: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        command_topic: _builtins.str = ...,
        state_topic: _builtins.str = ...,
        rate_hz: _builtins.float = ...,
        stale_zero_s: _builtins.float = ...,
        mounting: Global___MountingConfig | None = ...,
        sim_reaction_wheel: _driver_options_pb2.SimReactionWheelOptions | None = ...,
        basilisk_reaction_wheel: _driver_options_pb2.BasiliskReactionWheelOptions | None = ...,
        basilisk_magnetorquer: _driver_options_pb2.BasiliskMagnetorquerOptions | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["basilisk_magnetorquer", b"basilisk_magnetorquer", "basilisk_reaction_wheel", b"basilisk_reaction_wheel", "mounting", b"mounting", "options", b"options", "sim_reaction_wheel", b"sim_reaction_wheel"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["basilisk_magnetorquer", b"basilisk_magnetorquer", "basilisk_reaction_wheel", b"basilisk_reaction_wheel", "command_topic", b"command_topic", "mounting", b"mounting", "name", b"name", "options", b"options", "rate_hz", b"rate_hz", "sim_reaction_wheel", b"sim_reaction_wheel", "stale_zero_s", b"stale_zero_s", "state_topic", b"state_topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_options: _TypeAlias = _typing.Literal["sim_reaction_wheel", "basilisk_reaction_wheel", "basilisk_magnetorquer"]  # noqa: Y015
    _WhichOneofArgType_options: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_options) -> _WhichOneofReturnType_options | None: ...

Global___ActuatorConfig: _TypeAlias = ActuatorConfig  # noqa: Y015

@_typing.final
class ControlConfig(_message.Message):
    """The control loop: cadence + topics + one strategy, objective, estimator."""

    DESCRIPTOR: _descriptor.Descriptor

    RATE_HZ_FIELD_NUMBER: _builtins.int
    INPUT_TOPIC_FIELD_NUMBER: _builtins.int
    OUTPUT_TOPIC_FIELD_NUMBER: _builtins.int
    STALE_AFTER_S_FIELD_NUMBER: _builtins.int
    MAG_INPUT_TOPIC_FIELD_NUMBER: _builtins.int
    DIPOLE_OUTPUT_TOPIC_FIELD_NUMBER: _builtins.int
    SUN_INPUT_TOPIC_FIELD_NUMBER: _builtins.int
    STAR_INPUT_TOPIC_FIELD_NUMBER: _builtins.int
    RATE_DAMPING_FIELD_NUMBER: _builtins.int
    PID_FIELD_NUMBER: _builtins.int
    BDOT_FIELD_NUMBER: _builtins.int
    MOMENTUM_DUMP_FIELD_NUMBER: _builtins.int
    SUN_POINT_FIELD_NUMBER: _builtins.int
    NADIR_POINT_FIELD_NUMBER: _builtins.int
    ML_POLICY_FIELD_NUMBER: _builtins.int
    CONSTANT_RATE_FIELD_NUMBER: _builtins.int
    PASSTHROUGH_FIELD_NUMBER: _builtins.int
    TRIAD_FIELD_NUMBER: _builtins.int
    STAR_ATTITUDE_FIELD_NUMBER: _builtins.int
    rate_hz: _builtins.float
    input_topic: _builtins.str
    """measurement input"""
    output_topic: _builtins.str
    """actuator commands"""
    stale_after_s: _builtins.float
    """input age beyond which the measurement is not fresh"""
    mag_input_topic: _builtins.str
    """Magnetometer input for magnetic strategies; empty = none. The loop
    still paces on input_topic — the field rides along on the state.
    """
    dipole_output_topic: _builtins.str
    """Where dipole commands go when the strategy emits them alongside
    torque (momentum_dump, sun_point). Empty = the strategy must not
    emit both.
    """
    sun_input_topic: _builtins.str
    """Sun sensor input for attitude/pointing strategies; empty = none."""
    star_input_topic: _builtins.str
    """Star tracker input for attitude estimators; empty = none."""
    @_builtins.property
    def rate_damping(self) -> _control_options_pb2.RateDampingOptions: ...
    @_builtins.property
    def pid(self) -> _control_options_pb2.PidOptions: ...
    @_builtins.property
    def bdot(self) -> _control_options_pb2.BdotOptions: ...
    @_builtins.property
    def momentum_dump(self) -> _control_options_pb2.MomentumDumpOptions: ...
    @_builtins.property
    def sun_point(self) -> _control_options_pb2.SunPointOptions: ...
    @_builtins.property
    def nadir_point(self) -> _control_options_pb2.NadirPointOptions: ...
    @_builtins.property
    def ml_policy(self) -> _control_options_pb2.MlPolicyOptions: ...
    @_builtins.property
    def constant_rate(self) -> _control_options_pb2.ConstantRateOptions: ...
    @_builtins.property
    def passthrough(self) -> _control_options_pb2.PassthroughOptions: ...
    @_builtins.property
    def triad(self) -> _control_options_pb2.TriadOptions: ...
    @_builtins.property
    def star_attitude(self) -> _control_options_pb2.StarAttitudeOptions: ...
    def __init__(
        self,
        *,
        rate_hz: _builtins.float = ...,
        input_topic: _builtins.str = ...,
        output_topic: _builtins.str = ...,
        stale_after_s: _builtins.float = ...,
        mag_input_topic: _builtins.str = ...,
        dipole_output_topic: _builtins.str = ...,
        sun_input_topic: _builtins.str = ...,
        star_input_topic: _builtins.str = ...,
        rate_damping: _control_options_pb2.RateDampingOptions | None = ...,
        pid: _control_options_pb2.PidOptions | None = ...,
        bdot: _control_options_pb2.BdotOptions | None = ...,
        momentum_dump: _control_options_pb2.MomentumDumpOptions | None = ...,
        sun_point: _control_options_pb2.SunPointOptions | None = ...,
        nadir_point: _control_options_pb2.NadirPointOptions | None = ...,
        ml_policy: _control_options_pb2.MlPolicyOptions | None = ...,
        constant_rate: _control_options_pb2.ConstantRateOptions | None = ...,
        passthrough: _control_options_pb2.PassthroughOptions | None = ...,
        triad: _control_options_pb2.TriadOptions | None = ...,
        star_attitude: _control_options_pb2.StarAttitudeOptions | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bdot", b"bdot", "constant_rate", b"constant_rate", "estimator", b"estimator", "ml_policy", b"ml_policy", "momentum_dump", b"momentum_dump", "nadir_point", b"nadir_point", "objective", b"objective", "passthrough", b"passthrough", "pid", b"pid", "rate_damping", b"rate_damping", "star_attitude", b"star_attitude", "strategy", b"strategy", "sun_point", b"sun_point", "triad", b"triad"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bdot", b"bdot", "constant_rate", b"constant_rate", "dipole_output_topic", b"dipole_output_topic", "estimator", b"estimator", "input_topic", b"input_topic", "mag_input_topic", b"mag_input_topic", "ml_policy", b"ml_policy", "momentum_dump", b"momentum_dump", "nadir_point", b"nadir_point", "objective", b"objective", "output_topic", b"output_topic", "passthrough", b"passthrough", "pid", b"pid", "rate_damping", b"rate_damping", "rate_hz", b"rate_hz", "stale_after_s", b"stale_after_s", "star_attitude", b"star_attitude", "star_input_topic", b"star_input_topic", "strategy", b"strategy", "sun_input_topic", b"sun_input_topic", "sun_point", b"sun_point", "triad", b"triad"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_estimator: _TypeAlias = _typing.Literal["passthrough", "triad", "star_attitude"]  # noqa: Y015
    _WhichOneofArgType_estimator: _TypeAlias = _typing.Literal["estimator", b"estimator"]  # noqa: Y015
    _WhichOneofReturnType_objective: _TypeAlias = _typing.Literal["constant_rate"]  # noqa: Y015
    _WhichOneofArgType_objective: _TypeAlias = _typing.Literal["objective", b"objective"]  # noqa: Y015
    _WhichOneofReturnType_strategy: _TypeAlias = _typing.Literal["rate_damping", "pid", "bdot", "momentum_dump", "sun_point", "nadir_point", "ml_policy"]  # noqa: Y015
    _WhichOneofArgType_strategy: _TypeAlias = _typing.Literal["strategy", b"strategy"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_estimator) -> _WhichOneofReturnType_estimator | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_objective) -> _WhichOneofReturnType_objective | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_strategy) -> _WhichOneofReturnType_strategy | None: ...

Global___ControlConfig: _TypeAlias = ControlConfig  # noqa: Y015

@_typing.final
class VehicleConfig(_message.Message):
    """The whole spacecraft."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    BODY_FIELD_NUMBER: _builtins.int
    SENSORS_FIELD_NUMBER: _builtins.int
    ACTUATORS_FIELD_NUMBER: _builtins.int
    CONTROL_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    TELEMETRY_FIELD_NUMBER: _builtins.int
    FDIR_FIELD_NUMBER: _builtins.int
    COMMS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    description: _builtins.str
    @_builtins.property
    def body(self) -> Global___BodyConfig:
        """absent is allowed until a consumer needs it"""

    @_builtins.property
    def sensors(self) -> _containers.RepeatedCompositeFieldContainer[Global___SensorConfig]: ...
    @_builtins.property
    def actuators(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActuatorConfig]: ...
    @_builtins.property
    def control(self) -> Global___ControlConfig: ...
    @_builtins.property
    def mode(self) -> _mode_config_pb2.ModeConfig:
        """absent = defaults"""

    @_builtins.property
    def telemetry(self) -> _telemetry_config_pb2.TelemetryConfig:
        """absent = defaults"""

    @_builtins.property
    def fdir(self) -> _fdir_config_pb2.FdirConfig:
        """absent = no fault rules (no fdir service)"""

    @_builtins.property
    def comms(self) -> _comms_config_pb2.CommsConfig:
        """absent = no link service"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        body: Global___BodyConfig | None = ...,
        sensors: _abc.Iterable[Global___SensorConfig] | None = ...,
        actuators: _abc.Iterable[Global___ActuatorConfig] | None = ...,
        control: Global___ControlConfig | None = ...,
        mode: _mode_config_pb2.ModeConfig | None = ...,
        telemetry: _telemetry_config_pb2.TelemetryConfig | None = ...,
        fdir: _fdir_config_pb2.FdirConfig | None = ...,
        comms: _comms_config_pb2.CommsConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "comms", b"comms", "control", b"control", "fdir", b"fdir", "mode", b"mode", "telemetry", b"telemetry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actuators", b"actuators", "body", b"body", "comms", b"comms", "control", b"control", "description", b"description", "fdir", b"fdir", "mode", b"mode", "name", b"name", "sensors", b"sensors", "telemetry", b"telemetry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VehicleConfig: _TypeAlias = VehicleConfig  # noqa: Y015
