"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
HAL daemon message contract (PLAN.md §4) — the seam everything stands on.

Every sensor message embeds Header. The header carries the four fields the
architecture depends on: when the quantity was sampled, when it was
published, a per-source monotonic sequence number, and a validity word.
Daemons FLAG AND FORWARD — they never silently repair data; FDIR cannot
detect what the HAL papers over.

These .proto files are the single source of truth for inter-service
interfaces. Regenerate language bindings with tools/gen-protos.sh.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ValidityFlag:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ValidityFlagEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ValidityFlag.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    VALIDITY_FLAG_VALID: _ValidityFlag.ValueType  # 0
    """no fault flags set"""
    VALIDITY_FLAG_RANGE: _ValidityFlag.ValueType  # 1
    """beyond the device's DATASHEET measurement"""
    VALIDITY_FLAG_COMM: _ValidityFlag.ValueType  # 2
    """range — "the sensor cannot have measured
    this"; not an operational limit
    bus/communication error during read
    """
    VALIDITY_FLAG_CRC: _ValidityFlag.ValueType  # 4
    """checksum failure on the raw read"""
    VALIDITY_FLAG_STALE: _ValidityFlag.ValueType  # 8
    """no fresh sample within the freshness deadline"""
    VALIDITY_FLAG_SATURATED: _ValidityFlag.ValueType  # 16
    """pinned at the ADC/sensor rail — value is a"""

class ValidityFlag(_ValidityFlag, metaclass=_ValidityFlagEnumTypeWrapper):
    """Fault flags OR-ed into Header.validity. Zero means "no flags: valid".

    Scope: these are ACQUISITION facts — things only the publishing daemon
    can observe at the driver boundary ("is this number a real, fresh,
    uncorrupted measurement?"). Whether a real measurement is operationally
    NORMAL (thermal limits, rate-of-change, cross-channel consistency) is
    explicitly NOT the daemon's judgment — that is the FDIR limit checker
    (PLAN §8 L1), configured by ground-tunable rules, not baked into HALs.
    """

VALIDITY_FLAG_VALID: ValidityFlag.ValueType  # 0
"""no fault flags set"""
VALIDITY_FLAG_RANGE: ValidityFlag.ValueType  # 1
"""beyond the device's DATASHEET measurement"""
VALIDITY_FLAG_COMM: ValidityFlag.ValueType  # 2
"""range — "the sensor cannot have measured
this"; not an operational limit
bus/communication error during read
"""
VALIDITY_FLAG_CRC: ValidityFlag.ValueType  # 4
"""checksum failure on the raw read"""
VALIDITY_FLAG_STALE: ValidityFlag.ValueType  # 8
"""no fresh sample within the freshness deadline"""
VALIDITY_FLAG_SATURATED: ValidityFlag.ValueType  # 16
"""pinned at the ADC/sensor rail — value is a"""
Global___ValidityFlag: _TypeAlias = ValidityFlag  # noqa: Y015

@_typing.final
class Header(_message.Message):
    """Common envelope embedded by every sensor/telemetry message."""

    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FIELD_NUMBER: _builtins.int
    SAMPLE_TIME_NS_FIELD_NUMBER: _builtins.int
    PUBLISH_TIME_NS_FIELD_NUMBER: _builtins.int
    SEQ_FIELD_NUMBER: _builtins.int
    VALIDITY_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    """publishing daemon instance, e.g. "imu0" """
    sample_time_ns: _builtins.int
    """flight-clock time the quantity was sampled"""
    publish_time_ns: _builtins.int
    """flight-clock time the message was published"""
    seq: _builtins.int
    """per-source monotonic sequence number"""
    validity: _builtins.int
    """bitwise OR of ValidityFlag; 0 == valid"""
    def __init__(
        self,
        *,
        source: _builtins.str = ...,
        sample_time_ns: _builtins.int = ...,
        publish_time_ns: _builtins.int = ...,
        seq: _builtins.int = ...,
        validity: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["publish_time_ns", b"publish_time_ns", "sample_time_ns", b"sample_time_ns", "seq", b"seq", "source", b"source", "validity", b"validity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Header: _TypeAlias = Header  # noqa: Y015

@_typing.final
class ImuSample(_message.Message):
    """Inertial measurement sample. Body frame, SI units."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    GYRO_X_RAD_S_FIELD_NUMBER: _builtins.int
    GYRO_Y_RAD_S_FIELD_NUMBER: _builtins.int
    GYRO_Z_RAD_S_FIELD_NUMBER: _builtins.int
    ACCEL_X_M_S2_FIELD_NUMBER: _builtins.int
    ACCEL_Y_M_S2_FIELD_NUMBER: _builtins.int
    ACCEL_Z_M_S2_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    gyro_x_rad_s: _builtins.float
    gyro_y_rad_s: _builtins.float
    gyro_z_rad_s: _builtins.float
    accel_x_m_s2: _builtins.float
    accel_y_m_s2: _builtins.float
    accel_z_m_s2: _builtins.float
    temperature_c: _builtins.float
    @_builtins.property
    def header(self) -> Global___Header: ...
    def __init__(
        self,
        *,
        header: Global___Header | None = ...,
        gyro_x_rad_s: _builtins.float = ...,
        gyro_y_rad_s: _builtins.float = ...,
        gyro_z_rad_s: _builtins.float = ...,
        accel_x_m_s2: _builtins.float = ...,
        accel_y_m_s2: _builtins.float = ...,
        accel_z_m_s2: _builtins.float = ...,
        temperature_c: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accel_x_m_s2", b"accel_x_m_s2", "accel_y_m_s2", b"accel_y_m_s2", "accel_z_m_s2", b"accel_z_m_s2", "gyro_x_rad_s", b"gyro_x_rad_s", "gyro_y_rad_s", b"gyro_y_rad_s", "gyro_z_rad_s", b"gyro_z_rad_s", "header", b"header", "temperature_c", b"temperature_c"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ImuSample: _TypeAlias = ImuSample  # noqa: Y015

@_typing.final
class TemperatureSample(_message.Message):
    """Single-point temperature sample (e.g. a Jetson thermal zone)."""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    LOCATION_FIELD_NUMBER: _builtins.int
    temperature_c: _builtins.float
    location: _builtins.str
    """physical/logical measurement point, e.g. "tj-thermal" """
    @_builtins.property
    def header(self) -> Global___Header: ...
    def __init__(
        self,
        *,
        header: Global___Header | None = ...,
        temperature_c: _builtins.float = ...,
        location: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "location", b"location", "temperature_c", b"temperature_c"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TemperatureSample: _TypeAlias = TemperatureSample  # noqa: Y015
