# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flight.msgs import hal_pb2 as hal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\nflatsat.v1\x1a\thal.proto\"R\n\x0bPercentiles\x12\x0b\n\x03p50\x18\x01 \x01(\x01\x12\x0b\n\x03p99\x18\x02 \x01(\x01\x12\r\n\x05p99_9\x18\x03 \x01(\x01\x12\x0b\n\x03max\x18\x04 \x01(\x01\x12\r\n\x05\x63ount\x18\x05 \x01(\x04\"\xe5\x02\n\nLoopHealth\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x0f\n\x07vehicle\x18\x02 \x01(\t\x12\x17\n\x0f\x63onfig_checksum\x18\x03 \x01(\t\x12\x10\n\x08strategy\x18\x04 \x01(\t\x12\x11\n\tobjective\x18\x05 \x01(\t\x12\x0f\n\x07rate_hz\x18\x06 \x01(\x01\x12\x12\n\nscheduling\x18\x07 \x01(\t\x12\x14\n\x0c\x63pu_affinity\x18\x08 \x01(\t\x12\x15\n\rwindow_cycles\x18\t \x01(\x04\x12\x14\n\x0cstale_cycles\x18\n \x01(\x04\x12\x18\n\x10saturated_cycles\x18\x0b \x01(\x04\x12\x33\n\x12wakeup_lateness_us\x18\x0c \x01(\x0b\x32\x17.flatsat.v1.Percentiles\x12-\n\x0c\x65xec_time_us\x18\r \x01(\x0b\x32\x17.flatsat.v1.Percentiles\"\x98\x01\n\x0cSensorHealth\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.flatsat.v1.Header\x12\x0e\n\x06\x64river\x18\x02 \x01(\t\x12\x0f\n\x07rate_hz\x18\x03 \x01(\x01\x12\x16\n\x0ewindow_samples\x18\x04 \x01(\x04\x12\x17\n\x0f\x66lagged_samples\x18\x05 \x01(\x04\x12\x12\n\nflag_union\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERCENTILES']._serialized_start=39
  _globals['_PERCENTILES']._serialized_end=121
  _globals['_LOOPHEALTH']._serialized_start=124
  _globals['_LOOPHEALTH']._serialized_end=481
  _globals['_SENSORHEALTH']._serialized_start=484
  _globals['_SENSORHEALTH']._serialized_end=636
# @@protoc_insertion_point(module_scope)
