"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
COMMS COMPOSITION SCHEMA — the comms block of a vehicle file.

Every layer is selected by a oneof whose FIELD NAME is the registry
key, so the PHY and the framing swap independently and by config
alone: a Pluto GMSK modem, a lossy in-process loopback for campaigns
and CI, and (later) a learned receiver are peer implementations under
identical framing — which is what makes the learned-vs-classical
comparison honest.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LoopbackModemOptions(_message.Message):
    """---------------------------------------------------------------- PHY --

    In-process loopback: no hardware, no RF. Transmitted frames land in
    the paired receiver, optionally corrupted — the honest test PHY and
    the BER-campaign rig that needs no radio.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: _builtins.int
    FRAME_LOSS_FIELD_NUMBER: _builtins.int
    BIT_ERROR_RATE_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    channel: _builtins.str
    """paired endpoints share a channel name"""
    frame_loss: _builtins.float
    """fraction of frames dropped; absent = 0"""
    bit_error_rate: _builtins.float
    """per-bit flip probability; absent = 0"""
    seed: _builtins.int
    """corruption RNG seed; absent = unseeded"""
    def __init__(
        self,
        *,
        channel: _builtins.str = ...,
        frame_loss: _builtins.float | None = ...,
        bit_error_rate: _builtins.float | None = ...,
        seed: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bit_error_rate", b"_bit_error_rate", "_frame_loss", b"_frame_loss", "_seed", b"_seed", "bit_error_rate", b"bit_error_rate", "frame_loss", b"frame_loss", "seed", b"seed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bit_error_rate", b"_bit_error_rate", "_frame_loss", b"_frame_loss", "_seed", b"_seed", "bit_error_rate", b"bit_error_rate", "channel", b"channel", "frame_loss", b"frame_loss", "seed", b"seed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bit_error_rate: _TypeAlias = _typing.Literal["bit_error_rate"]  # noqa: Y015
    _WhichOneofArgType__bit_error_rate: _TypeAlias = _typing.Literal["_bit_error_rate", b"_bit_error_rate"]  # noqa: Y015
    _WhichOneofReturnType__frame_loss: _TypeAlias = _typing.Literal["frame_loss"]  # noqa: Y015
    _WhichOneofArgType__frame_loss: _TypeAlias = _typing.Literal["_frame_loss", b"_frame_loss"]  # noqa: Y015
    _WhichOneofReturnType__seed: _TypeAlias = _typing.Literal["seed"]  # noqa: Y015
    _WhichOneofArgType__seed: _TypeAlias = _typing.Literal["_seed", b"_seed"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bit_error_rate) -> _WhichOneofReturnType__bit_error_rate | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__frame_loss) -> _WhichOneofReturnType__frame_loss | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__seed) -> _WhichOneofReturnType__seed | None: ...

Global___LoopbackModemOptions: _TypeAlias = LoopbackModemOptions  # noqa: Y015

@_typing.final
class KissModemOptions(_message.Message):
    """KISS over TCP: no DSP here at all. An external process owns the radio
    — a gr-satellites flowgraph, a GNU Radio design, Direwolf, a hardware
    TNC — and this carries frames to and from it over the framing that
    amateur and cubesat ground software has spoken for decades. Pair it
    with the ccsds framer to tunnel our own frames over any TNC, or with
    a pass-through framer to let the far side do the deframing with
    somebody else's standard implementation.

    This modem cannot radiate by itself, so the transmit gate lives in
    the process at the far end of the socket, not here.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HOST_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    KISS_PORT_FIELD_NUMBER: _builtins.int
    host: _builtins.str
    """where the radio process listens; empty = 127.0.0.1"""
    port: _builtins.int
    """TCP port; 0 = 8001, the conventional KISS port"""
    kiss_port: _builtins.int
    """KISS port number inside the protocol, not TCP"""
    def __init__(
        self,
        *,
        host: _builtins.str = ...,
        port: _builtins.int = ...,
        kiss_port: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["host", b"host", "kiss_port", b"kiss_port", "port", b"port"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KissModemOptions: _TypeAlias = KissModemOptions  # noqa: Y015

@_typing.final
class PlutoGmskModemOptions(_message.Message):
    """ADALM-Pluto over GNU Radio, GMSK — the proven baseline PHY (BER 0.00
    framed loopback, 2026-07-23). RF SAFETY: transmit is refused unless
    transmit_ack is explicitly true, mirroring the radio scripts'
    --transmit gate (FSW-RADIO-001); receive needs no acknowledgement.
    """

    DESCRIPTOR: _descriptor.Descriptor

    URI_FIELD_NUMBER: _builtins.int
    CENTER_FREQ_HZ_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_HZ_FIELD_NUMBER: _builtins.int
    OFFSET_HZ_FIELD_NUMBER: _builtins.int
    SAMPLES_PER_SYMBOL_FIELD_NUMBER: _builtins.int
    TX_ATTENUATION_DB_FIELD_NUMBER: _builtins.int
    TRANSMIT_ACK_FIELD_NUMBER: _builtins.int
    GROUND_URI_FIELD_NUMBER: _builtins.int
    uri: _builtins.str
    """e.g. "ip:192.168.2.1" """
    center_freq_hz: _builtins.float
    sample_rate_hz: _builtins.float
    offset_hz: _builtins.float
    """keep energy OFF DC (zero-IF lesson); absent = 250e3"""
    samples_per_symbol: _builtins.int
    """absent = 8"""
    tx_attenuation_db: _builtins.int
    """absent = 60 (near-minimum power)"""
    transmit_ack: _builtins.bool
    """MUST be true to enable TX. Cabled + 30 dB pads only."""
    ground_uri: _builtins.str
    """Two-radio desks: the GROUND endpoint's radio, when it is a
    different device than the flight endpoint's (e.g. two Plutos on
    one host after the identity fix). Absent = both endpoints use uri.
    """
    def __init__(
        self,
        *,
        uri: _builtins.str = ...,
        center_freq_hz: _builtins.float = ...,
        sample_rate_hz: _builtins.float = ...,
        offset_hz: _builtins.float | None = ...,
        samples_per_symbol: _builtins.int | None = ...,
        tx_attenuation_db: _builtins.int | None = ...,
        transmit_ack: _builtins.bool = ...,
        ground_uri: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_ground_uri", b"_ground_uri", "_offset_hz", b"_offset_hz", "_samples_per_symbol", b"_samples_per_symbol", "_tx_attenuation_db", b"_tx_attenuation_db", "ground_uri", b"ground_uri", "offset_hz", b"offset_hz", "samples_per_symbol", b"samples_per_symbol", "tx_attenuation_db", b"tx_attenuation_db"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_ground_uri", b"_ground_uri", "_offset_hz", b"_offset_hz", "_samples_per_symbol", b"_samples_per_symbol", "_tx_attenuation_db", b"_tx_attenuation_db", "center_freq_hz", b"center_freq_hz", "ground_uri", b"ground_uri", "offset_hz", b"offset_hz", "sample_rate_hz", b"sample_rate_hz", "samples_per_symbol", b"samples_per_symbol", "transmit_ack", b"transmit_ack", "tx_attenuation_db", b"tx_attenuation_db", "uri", b"uri"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__ground_uri: _TypeAlias = _typing.Literal["ground_uri"]  # noqa: Y015
    _WhichOneofArgType__ground_uri: _TypeAlias = _typing.Literal["_ground_uri", b"_ground_uri"]  # noqa: Y015
    _WhichOneofReturnType__offset_hz: _TypeAlias = _typing.Literal["offset_hz"]  # noqa: Y015
    _WhichOneofArgType__offset_hz: _TypeAlias = _typing.Literal["_offset_hz", b"_offset_hz"]  # noqa: Y015
    _WhichOneofReturnType__samples_per_symbol: _TypeAlias = _typing.Literal["samples_per_symbol"]  # noqa: Y015
    _WhichOneofArgType__samples_per_symbol: _TypeAlias = _typing.Literal["_samples_per_symbol", b"_samples_per_symbol"]  # noqa: Y015
    _WhichOneofReturnType__tx_attenuation_db: _TypeAlias = _typing.Literal["tx_attenuation_db"]  # noqa: Y015
    _WhichOneofArgType__tx_attenuation_db: _TypeAlias = _typing.Literal["_tx_attenuation_db", b"_tx_attenuation_db"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ground_uri) -> _WhichOneofReturnType__ground_uri | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__offset_hz) -> _WhichOneofReturnType__offset_hz | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__samples_per_symbol) -> _WhichOneofReturnType__samples_per_symbol | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__tx_attenuation_db) -> _WhichOneofReturnType__tx_attenuation_db | None: ...

Global___PlutoGmskModemOptions: _TypeAlias = PlutoGmskModemOptions  # noqa: Y015

@_typing.final
class CcsdsFramerOptions(_message.Message):
    """-------------------------------------------------------------- framing --

    CCSDS-style: attached sync marker, length, payload, CRC-32. A
    corrupted frame is DROPPED and counted, never delivered — the link's
    flag-and-forward equivalent.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAX_PAYLOAD_BYTES_FIELD_NUMBER: _builtins.int
    max_payload_bytes: _builtins.int
    """sanity bound on the length field; absent = 4096"""
    def __init__(
        self,
        *,
        max_payload_bytes: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_max_payload_bytes", b"_max_payload_bytes", "max_payload_bytes", b"max_payload_bytes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_max_payload_bytes", b"_max_payload_bytes", "max_payload_bytes", b"max_payload_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__max_payload_bytes: _TypeAlias = _typing.Literal["max_payload_bytes"]  # noqa: Y015
    _WhichOneofArgType__max_payload_bytes: _TypeAlias = _typing.Literal["_max_payload_bytes", b"_max_payload_bytes"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_payload_bytes) -> _WhichOneofReturnType__max_payload_bytes | None: ...

Global___CcsdsFramerOptions: _TypeAlias = CcsdsFramerOptions  # noqa: Y015

@_typing.final
class ContactScheduleConfig(_message.Message):
    """------------------------------------------------------------------ link --

    Simulated pass geometry: the radio is gated even though both radios
    sit on one desk. Telemetry accumulates between passes and dumps on
    contact (PLAN §6). Absent = always in contact.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PERIOD_S_FIELD_NUMBER: _builtins.int
    DURATION_S_FIELD_NUMBER: _builtins.int
    period_s: _builtins.float
    """pass repeat interval"""
    duration_s: _builtins.float
    """contact length within each period"""
    def __init__(
        self,
        *,
        period_s: _builtins.float = ...,
        duration_s: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_s", b"duration_s", "period_s", b"period_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ContactScheduleConfig: _TypeAlias = ContactScheduleConfig  # noqa: Y015

@_typing.final
class CommsConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DOWNLINK_TOPICS_FIELD_NUMBER: _builtins.int
    SEGMENT_BYTES_FIELD_NUMBER: _builtins.int
    QUEUE_LIMIT_FIELD_NUMBER: _builtins.int
    CONTACT_FIELD_NUMBER: _builtins.int
    UPLINK_TOPICS_FIELD_NUMBER: _builtins.int
    LOOPBACK_FIELD_NUMBER: _builtins.int
    PLUTO_GMSK_FIELD_NUMBER: _builtins.int
    KISS_FIELD_NUMBER: _builtins.int
    CCSDS_FIELD_NUMBER: _builtins.int
    segment_bytes: _builtins.int
    """payload bytes per segment; absent = 512"""
    queue_limit: _builtins.int
    """stored messages between passes; absent = 10000"""
    @_builtins.property
    def downlink_topics(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Bus topics whose messages are queued for downlink. Explicit by
        design — the link carries named traffic, never the whole bus.
        """

    @_builtins.property
    def contact(self) -> Global___ContactScheduleConfig:
        """absent = always in contact"""

    @_builtins.property
    def uplink_topics(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Topics the GROUND side queues for uplink (commands, artifact
        chunks). Directional on purpose: the link is asymmetric, and an
        allowlist that differs by direction is what keeps a republished
        arrival on one side from echoing straight back across the link.
        """

    @_builtins.property
    def loopback(self) -> Global___LoopbackModemOptions: ...
    @_builtins.property
    def pluto_gmsk(self) -> Global___PlutoGmskModemOptions: ...
    @_builtins.property
    def kiss(self) -> Global___KissModemOptions: ...
    @_builtins.property
    def ccsds(self) -> Global___CcsdsFramerOptions: ...
    def __init__(
        self,
        *,
        downlink_topics: _abc.Iterable[_builtins.str] | None = ...,
        segment_bytes: _builtins.int | None = ...,
        queue_limit: _builtins.int | None = ...,
        contact: Global___ContactScheduleConfig | None = ...,
        uplink_topics: _abc.Iterable[_builtins.str] | None = ...,
        loopback: Global___LoopbackModemOptions | None = ...,
        pluto_gmsk: Global___PlutoGmskModemOptions | None = ...,
        kiss: Global___KissModemOptions | None = ...,
        ccsds: Global___CcsdsFramerOptions | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_queue_limit", b"_queue_limit", "_segment_bytes", b"_segment_bytes", "ccsds", b"ccsds", "contact", b"contact", "framer", b"framer", "kiss", b"kiss", "loopback", b"loopback", "modem", b"modem", "pluto_gmsk", b"pluto_gmsk", "queue_limit", b"queue_limit", "segment_bytes", b"segment_bytes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_queue_limit", b"_queue_limit", "_segment_bytes", b"_segment_bytes", "ccsds", b"ccsds", "contact", b"contact", "downlink_topics", b"downlink_topics", "framer", b"framer", "kiss", b"kiss", "loopback", b"loopback", "modem", b"modem", "pluto_gmsk", b"pluto_gmsk", "queue_limit", b"queue_limit", "segment_bytes", b"segment_bytes", "uplink_topics", b"uplink_topics"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__queue_limit: _TypeAlias = _typing.Literal["queue_limit"]  # noqa: Y015
    _WhichOneofArgType__queue_limit: _TypeAlias = _typing.Literal["_queue_limit", b"_queue_limit"]  # noqa: Y015
    _WhichOneofReturnType__segment_bytes: _TypeAlias = _typing.Literal["segment_bytes"]  # noqa: Y015
    _WhichOneofArgType__segment_bytes: _TypeAlias = _typing.Literal["_segment_bytes", b"_segment_bytes"]  # noqa: Y015
    _WhichOneofReturnType_framer: _TypeAlias = _typing.Literal["ccsds"]  # noqa: Y015
    _WhichOneofArgType_framer: _TypeAlias = _typing.Literal["framer", b"framer"]  # noqa: Y015
    _WhichOneofReturnType_modem: _TypeAlias = _typing.Literal["loopback", "pluto_gmsk", "kiss"]  # noqa: Y015
    _WhichOneofArgType_modem: _TypeAlias = _typing.Literal["modem", b"modem"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__queue_limit) -> _WhichOneofReturnType__queue_limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__segment_bytes) -> _WhichOneofReturnType__segment_bytes | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_framer) -> _WhichOneofReturnType_framer | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_modem) -> _WhichOneofReturnType_modem | None: ...

Global___CommsConfig: _TypeAlias = CommsConfig  # noqa: Y015
