"""A/B artifact slots: activate by command, roll back on regression.

The decide half of the C1 path, and the place the four-tier versioning
philosophy becomes code: the MECHANISM is uniform (a pointer moves), the
AUTHORITY is gated.

  * **Activation requires ground authority.** Bytes arriving over RF do
    not deploy themselves.
  * **Activation is refused while the system is Safe.** Safe mode's
    survival law ships in Tier 1 and is never displaced by an uplinked
    component; you do not hot-swap during a safing event.
  * **Rollback is always allowed**, needs no authority, and works while
    Safe — reverting to the last known-good version is a toward-safety
    action, exactly like requesting Safe itself.

Activation moves a POINTER and records the previous version; it never
executes the artifact. Consumers read the active pointer when they next
start, so a bad activation costs a restart, not a running system.
"""

from __future__ import annotations

import shutil
import time
from pathlib import Path

from flatsat.core.config import load_textproto
from flatsat.msgs import mode_pb2, uplink_pb2


class ActivationRefused(Exception):
    """An activation was blocked by an authority or mode gate."""


class SlotManager:
    """Owns the active/previous pointers for every uplinked artifact."""

    def __init__(self, slots_dir: Path | str) -> None:
        """Bind the manager to its slots directory.

        Args:
            slots_dir: Where activated artifacts and their slot state
                live. Created if absent.
        """
        self.slots_dir = Path(slots_dir).expanduser()
        self.slots_dir.mkdir(parents=True, exist_ok=True)
        self.refused_activations = 0

    # ------------------------------------------------------------- state --

    def _state_path(self, name: str) -> Path:
        """Path of one artifact's persisted slot state.

        Args:
            name: Artifact name.

        Returns:
            The state file path.
        """
        return self.slots_dir / f"{name}.slots.txtpb"

    def state(self, name: str) -> uplink_pb2.ArtifactSlots:
        """Read one artifact's slot state.

        Args:
            name: Artifact name.

        Returns:
            The persisted state, or an empty state when nothing has ever
            been activated.
        """
        slots = uplink_pb2.ArtifactSlots()
        path = self._state_path(name)
        if path.is_file():
            # Parse into an EMPTY message: text_format rejects a scalar
            # that is already set, so pre-filling name would fail here.
            load_textproto(path, slots)
        slots.name = name
        return slots

    def _write_state(self, slots: uplink_pb2.ArtifactSlots) -> None:
        """Persist one artifact's slot state as textproto.

        Args:
            slots: The state to write.
        """
        header = (
            "# proto-file: flatsat/msgs/uplink.proto\n"
            "# proto-message: flatsat.v1.ArtifactSlots\n"
            "# GENERATED by the uplink service — records which uplinked\n"
            "# version is live and what rollback reverts to.\n"
        )
        self._state_path(slots.name).write_text(header + str(slots))

    def all_states(self) -> list[uplink_pb2.ArtifactSlots]:
        """Slot state for every artifact that has ever been activated.

        Returns:
            States, sorted by artifact name.
        """
        states = []
        for path in sorted(self.slots_dir.glob("*.slots.txtpb")):
            slots = uplink_pb2.ArtifactSlots()
            load_textproto(path, slots)
            states.append(slots)
        return states

    def active_path(self, name: str) -> Path | None:
        """Where the currently active version of an artifact lives.

        Args:
            name: Artifact name.

        Returns:
            Path to the live bytes, or None when nothing is active.
        """
        version = self.state(name).active_version
        if not version:
            return None
        candidate = self.slots_dir / f"{name}@{version}" / "artifact.bin"
        return candidate if candidate.is_file() else None

    # -------------------------------------------------------- transitions --

    def activate(
        self,
        name: str,
        version: str,
        staged_path: Path | None,
        ground_authority: bool,
        mode: mode_pb2.SystemMode.ValueType | None = None,
    ) -> uplink_pb2.ArtifactSlots:
        """Make a staged version the active one.

        Args:
            name: Artifact name.
            version: Staged version to activate.
            staged_path: Path to the verified staged bytes.
            ground_authority: Whether the command carries ground
                authority. Required.
            mode: Current system mode, when known. Activation is refused
                in SAFE.

        Returns:
            The updated slot state.

        Raises:
            ActivationRefused: On missing authority, on SAFE mode, or
                when the version was never staged and verified.
        """
        if not ground_authority:
            self.refused_activations += 1
            raise ActivationRefused("activation requires ground authority")
        if mode == mode_pb2.SYSTEM_MODE_SAFE:
            self.refused_activations += 1
            raise ActivationRefused("activation refused in SAFE: survival law is not swappable")
        if staged_path is None or not staged_path.is_file():
            self.refused_activations += 1
            raise ActivationRefused(f"{name}@{version} is not staged and verified")

        target = self.slots_dir / f"{name}@{version}"
        target.mkdir(parents=True, exist_ok=True)
        shutil.copy2(staged_path, target / "artifact.bin")

        slots = self.state(name)
        if slots.active_version and slots.active_version != version:
            slots.previous_version = slots.active_version  # the rollback target
        slots.active_version = version
        slots.activated_time_ns = time.time_ns()
        self._write_state(slots)
        return slots

    def rollback(self, name: str) -> uplink_pb2.ArtifactSlots:
        """Revert to the previous version.

        Needs no authority and works in any mode: returning to the last
        known-good version is a toward-safety action.

        Args:
            name: Artifact name.

        Returns:
            The updated slot state.

        Raises:
            ActivationRefused: When there is nothing to revert to —
                honest refusal beats pretending a rollback happened.
        """
        slots = self.state(name)
        if not slots.previous_version:
            raise ActivationRefused(f"{name}: no previous version to roll back to")
        slots.active_version, slots.previous_version = (
            slots.previous_version,
            slots.active_version,
        )
        slots.activated_time_ns = time.time_ns()
        self._write_state(slots)
        return slots
