# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/sim/mission.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/sim/mission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66latsat/sim/mission.proto\x12\nflatsat.v1\"\x81\x01\n\x15SuccessCriteriaConfig\x12 \n\x13max_omega_mag_rad_s\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x14\n\x0crequire_mode\x18\x02 \x01(\t\x12\x18\n\x10require_all_acks\x18\x03 \x01(\x08\x42\x16\n\x14_max_omega_mag_rad_s\"\xda\x01\n\x0bPhaseConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nduration_s\x18\x02 \x01(\x01\x12\x14\n\x0crequest_mode\x18\x03 \x01(\t\x12 \n\x18request_ground_authority\x18\x04 \x01(\x08\x12\x1e\n\x16\x65xpect_request_refused\x18\x05 \x01(\x08\x12\x32\n\x07success\x18\x06 \x01(\x0b\x32!.flatsat.v1.SuccessCriteriaConfig\x12\x1d\n\x15inject_truth_blackout\x18\x07 \x01(\x08\"\xb0\x01\n\rMissionConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07vehicle\x18\x03 \x01(\t\x12\x14\n\x0comega0_rad_s\x18\x04 \x03(\x01\x12\x1a\n\rplant_rate_hz\x18\x05 \x01(\x01H\x00\x88\x01\x01\x12\'\n\x06phases\x18\x06 \x03(\x0b\x32\x17.flatsat.v1.PhaseConfigB\x10\n\x0e_plant_rate_hzb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.sim.mission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUCCESSCRITERIACONFIG']._serialized_start=42
  _globals['_SUCCESSCRITERIACONFIG']._serialized_end=171
  _globals['_PHASECONFIG']._serialized_start=174
  _globals['_PHASECONFIG']._serialized_end=392
  _globals['_MISSIONCONFIG']._serialized_start=395
  _globals['_MISSIONCONFIG']._serialized_end=571
# @@protoc_insertion_point(module_scope)
