"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
MISSION PROFILE SCHEMA — what a config/missions/*.txtpb file fills out.

A mission is data: initial conditions, a phase timeline (each phase
optionally commanding a mode transition), and per-phase success
criteria, executed by the generic scenario runner
(flatsat/sim/scenario.py). The same files script real Basilisk HIL
campaigns — the Mac's bridge stands behind the same topics as the
local plant.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SuccessCriteriaConfig(_message.Message):
    """What must be true at the end of a phase."""

    DESCRIPTOR: _descriptor.Descriptor

    MAX_OMEGA_MAG_RAD_S_FIELD_NUMBER: _builtins.int
    REQUIRE_MODE_FIELD_NUMBER: _builtins.int
    REQUIRE_ALL_ACKS_FIELD_NUMBER: _builtins.int
    max_omega_mag_rad_s: _builtins.float
    """plant |omega| bound; absent skips"""
    require_mode: _builtins.str
    """bare mode name (NOMINAL, SAFE, ...); empty skips"""
    require_all_acks: _builtins.bool
    """every registered app acked the current seq"""
    def __init__(
        self,
        *,
        max_omega_mag_rad_s: _builtins.float | None = ...,
        require_mode: _builtins.str = ...,
        require_all_acks: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_max_omega_mag_rad_s", b"_max_omega_mag_rad_s", "max_omega_mag_rad_s", b"max_omega_mag_rad_s"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_max_omega_mag_rad_s", b"_max_omega_mag_rad_s", "max_omega_mag_rad_s", b"max_omega_mag_rad_s", "require_all_acks", b"require_all_acks", "require_mode", b"require_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__max_omega_mag_rad_s: _TypeAlias = _typing.Literal["max_omega_mag_rad_s"]  # noqa: Y015
    _WhichOneofArgType__max_omega_mag_rad_s: _TypeAlias = _typing.Literal["_max_omega_mag_rad_s", b"_max_omega_mag_rad_s"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_omega_mag_rad_s) -> _WhichOneofReturnType__max_omega_mag_rad_s | None: ...

Global___SuccessCriteriaConfig: _TypeAlias = SuccessCriteriaConfig  # noqa: Y015

@_typing.final
class PhaseConfig(_message.Message):
    """One phase of the timeline.
    A phase is also a SUB-MISSION: the same message serves inline in a
    mission and standing alone in config/submissions/*.txtpb, so a
    reusable building block needs no second schema. A phase that sets
    `use` loads that file as its base and overrides whatever it also
    sets, which is plain proto3 merge semantics — an unset scalar leaves
    the base's value alone.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DURATION_S_FIELD_NUMBER: _builtins.int
    REQUEST_MODE_FIELD_NUMBER: _builtins.int
    REQUEST_GROUND_AUTHORITY_FIELD_NUMBER: _builtins.int
    EXPECT_REQUEST_REFUSED_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    INJECT_TRUTH_BLACKOUT_FIELD_NUMBER: _builtins.int
    USE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    duration_s: _builtins.float
    """how long the phase runs before judgment"""
    request_mode: _builtins.str
    """bare mode name to request at start; empty = none"""
    request_ground_authority: _builtins.bool
    """runner plays ground (true) vs FDIR (false)"""
    expect_request_refused: _builtins.bool
    """phase EXPECTS refusal — asserts the asymmetry"""
    inject_truth_blackout: _builtins.bool
    """Fault injection: kill the truth source at phase start (the plant
    stops publishing — the bench-without-bridge signature). Downstream
    must degrade honestly: STALE flags, wheel zeroing, FDIR safing.
    """
    use: _builtins.str
    """Path to a saved sub-mission to use as this phase's base, relative
    to the repository root. Empty = the phase is defined entirely here.
    """
    @_builtins.property
    def success(self) -> Global___SuccessCriteriaConfig: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        duration_s: _builtins.float = ...,
        request_mode: _builtins.str = ...,
        request_ground_authority: _builtins.bool = ...,
        expect_request_refused: _builtins.bool = ...,
        success: Global___SuccessCriteriaConfig | None = ...,
        inject_truth_blackout: _builtins.bool = ...,
        use: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_s", b"duration_s", "expect_request_refused", b"expect_request_refused", "inject_truth_blackout", b"inject_truth_blackout", "name", b"name", "request_ground_authority", b"request_ground_authority", "request_mode", b"request_mode", "success", b"success", "use", b"use"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PhaseConfig: _TypeAlias = PhaseConfig  # noqa: Y015

@_typing.final
class OrbitConfig(_message.Message):
    """The whole mission.
    Where and when the vehicle flies. A saved orbit in config/orbits is a
    reusable environment the same way a sub-mission is a reusable phase.

    Leaving inclination unset asks for the SUN-SYNCHRONOUS inclination at
    this altitude, which is intent rather than a number: "keep local solar
    time fixed" is the property a mission wants, and the ~97.4 degrees
    that delivers it at 500 km is a consequence nobody should hand-copy.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    ALTITUDE_M_FIELD_NUMBER: _builtins.int
    INCLINATION_DEG_FIELD_NUMBER: _builtins.int
    RAAN_DEG_FIELD_NUMBER: _builtins.int
    ECCENTRICITY_FIELD_NUMBER: _builtins.int
    ARG_PERIAPSIS_DEG_FIELD_NUMBER: _builtins.int
    TRUE_ANOMALY_DEG_FIELD_NUMBER: _builtins.int
    EPOCH_GMST_DEG_FIELD_NUMBER: _builtins.int
    EPOCH_SOLAR_ANGLE_DEG_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    description: _builtins.str
    altitude_m: _builtins.float
    """circular orbit altitude"""
    inclination_deg: _builtins.float
    """absent = sun-synchronous here"""
    raan_deg: _builtins.float
    """ascending node at epoch"""
    eccentricity: _builtins.float
    arg_periapsis_deg: _builtins.float
    true_anomaly_deg: _builtins.float
    """position along the orbit at epoch"""
    epoch_gmst_deg: _builtins.float
    """Greenwich sidereal angle at epoch"""
    epoch_solar_angle_deg: _builtins.float
    """solar longitude at epoch"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        altitude_m: _builtins.float = ...,
        inclination_deg: _builtins.float | None = ...,
        raan_deg: _builtins.float = ...,
        eccentricity: _builtins.float = ...,
        arg_periapsis_deg: _builtins.float = ...,
        true_anomaly_deg: _builtins.float = ...,
        epoch_gmst_deg: _builtins.float = ...,
        epoch_solar_angle_deg: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_inclination_deg", b"_inclination_deg", "inclination_deg", b"inclination_deg"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_inclination_deg", b"_inclination_deg", "altitude_m", b"altitude_m", "arg_periapsis_deg", b"arg_periapsis_deg", "description", b"description", "eccentricity", b"eccentricity", "epoch_gmst_deg", b"epoch_gmst_deg", "epoch_solar_angle_deg", b"epoch_solar_angle_deg", "inclination_deg", b"inclination_deg", "name", b"name", "raan_deg", b"raan_deg", "true_anomaly_deg", b"true_anomaly_deg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__inclination_deg: _TypeAlias = _typing.Literal["inclination_deg"]  # noqa: Y015
    _WhichOneofArgType__inclination_deg: _TypeAlias = _typing.Literal["_inclination_deg", b"_inclination_deg"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__inclination_deg) -> _WhichOneofReturnType__inclination_deg | None: ...

Global___OrbitConfig: _TypeAlias = OrbitConfig  # noqa: Y015

@_typing.final
class MissionConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    VEHICLE_FIELD_NUMBER: _builtins.int
    OMEGA0_RAD_S_FIELD_NUMBER: _builtins.int
    PLANT_RATE_HZ_FIELD_NUMBER: _builtins.int
    PHASES_FIELD_NUMBER: _builtins.int
    ORBIT_FIELD_NUMBER: _builtins.int
    SIGMA0_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    description: _builtins.str
    vehicle: _builtins.str
    """vehicle file the mission flies"""
    plant_rate_hz: _builtins.float
    """absent = 100"""
    orbit: _builtins.str
    """Saved orbit file, relative to the repository root. Empty means the
    run has no orbit: attitude-only, which is all a reaction-wheel
    detumble needs and all this harness modelled before magnetics.
    """
    @_builtins.property
    def omega0_rad_s(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """initial plant body rates, 3 values"""

    @_builtins.property
    def phases(self) -> _containers.RepeatedCompositeFieldContainer[Global___PhaseConfig]: ...
    @_builtins.property
    def sigma0(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Attitude at epoch as an MRP. A deployer releases with an arbitrary
        orientation, not an identity one.
        """

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        vehicle: _builtins.str = ...,
        omega0_rad_s: _abc.Iterable[_builtins.float] | None = ...,
        plant_rate_hz: _builtins.float | None = ...,
        phases: _abc.Iterable[Global___PhaseConfig] | None = ...,
        orbit: _builtins.str = ...,
        sigma0: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_plant_rate_hz", b"_plant_rate_hz", "plant_rate_hz", b"plant_rate_hz"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_plant_rate_hz", b"_plant_rate_hz", "description", b"description", "name", b"name", "omega0_rad_s", b"omega0_rad_s", "orbit", b"orbit", "phases", b"phases", "plant_rate_hz", b"plant_rate_hz", "sigma0", b"sigma0", "vehicle", b"vehicle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__plant_rate_hz: _TypeAlias = _typing.Literal["plant_rate_hz"]  # noqa: Y015
    _WhichOneofArgType__plant_rate_hz: _TypeAlias = _typing.Literal["_plant_rate_hz", b"_plant_rate_hz"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__plant_rate_hz) -> _WhichOneofReturnType__plant_rate_hz | None: ...

Global___MissionConfig: _TypeAlias = MissionConfig  # noqa: Y015
