"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
MISSION PROFILE SCHEMA — what a config/missions/*.txtpb file fills out.

A mission is data: initial conditions, a phase timeline (each phase
optionally commanding a mode transition), and per-phase success
criteria, executed by the generic scenario runner
(flatsat/sim/scenario.py). The same files script real Basilisk HIL
campaigns — the Mac's bridge stands behind the same topics as the
local plant.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SuccessCriteriaConfig(_message.Message):
    """What must be true at the end of a phase."""

    DESCRIPTOR: _descriptor.Descriptor

    MAX_OMEGA_MAG_RAD_S_FIELD_NUMBER: _builtins.int
    REQUIRE_MODE_FIELD_NUMBER: _builtins.int
    REQUIRE_ALL_ACKS_FIELD_NUMBER: _builtins.int
    max_omega_mag_rad_s: _builtins.float
    """plant |omega| bound; absent skips"""
    require_mode: _builtins.str
    """bare mode name (NOMINAL, SAFE, ...); empty skips"""
    require_all_acks: _builtins.bool
    """every registered app acked the current seq"""
    def __init__(
        self,
        *,
        max_omega_mag_rad_s: _builtins.float | None = ...,
        require_mode: _builtins.str = ...,
        require_all_acks: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_max_omega_mag_rad_s", b"_max_omega_mag_rad_s", "max_omega_mag_rad_s", b"max_omega_mag_rad_s"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_max_omega_mag_rad_s", b"_max_omega_mag_rad_s", "max_omega_mag_rad_s", b"max_omega_mag_rad_s", "require_all_acks", b"require_all_acks", "require_mode", b"require_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__max_omega_mag_rad_s: _TypeAlias = _typing.Literal["max_omega_mag_rad_s"]  # noqa: Y015
    _WhichOneofArgType__max_omega_mag_rad_s: _TypeAlias = _typing.Literal["_max_omega_mag_rad_s", b"_max_omega_mag_rad_s"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_omega_mag_rad_s) -> _WhichOneofReturnType__max_omega_mag_rad_s | None: ...

Global___SuccessCriteriaConfig: _TypeAlias = SuccessCriteriaConfig  # noqa: Y015

@_typing.final
class PhaseConfig(_message.Message):
    """One phase of the timeline."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DURATION_S_FIELD_NUMBER: _builtins.int
    REQUEST_MODE_FIELD_NUMBER: _builtins.int
    REQUEST_GROUND_AUTHORITY_FIELD_NUMBER: _builtins.int
    EXPECT_REQUEST_REFUSED_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    duration_s: _builtins.float
    """how long the phase runs before judgment"""
    request_mode: _builtins.str
    """bare mode name to request at start; empty = none"""
    request_ground_authority: _builtins.bool
    """runner plays ground (true) vs FDIR (false)"""
    expect_request_refused: _builtins.bool
    """phase EXPECTS refusal — asserts the asymmetry"""
    @_builtins.property
    def success(self) -> Global___SuccessCriteriaConfig: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        duration_s: _builtins.float = ...,
        request_mode: _builtins.str = ...,
        request_ground_authority: _builtins.bool = ...,
        expect_request_refused: _builtins.bool = ...,
        success: Global___SuccessCriteriaConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_s", b"duration_s", "expect_request_refused", b"expect_request_refused", "name", b"name", "request_ground_authority", b"request_ground_authority", "request_mode", b"request_mode", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PhaseConfig: _TypeAlias = PhaseConfig  # noqa: Y015

@_typing.final
class MissionConfig(_message.Message):
    """The whole mission."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    VEHICLE_FIELD_NUMBER: _builtins.int
    OMEGA0_RAD_S_FIELD_NUMBER: _builtins.int
    PLANT_RATE_HZ_FIELD_NUMBER: _builtins.int
    PHASES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    description: _builtins.str
    vehicle: _builtins.str
    """vehicle file the mission flies"""
    plant_rate_hz: _builtins.float
    """absent = 100"""
    @_builtins.property
    def omega0_rad_s(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """initial plant body rates, 3 values"""

    @_builtins.property
    def phases(self) -> _containers.RepeatedCompositeFieldContainer[Global___PhaseConfig]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        vehicle: _builtins.str = ...,
        omega0_rad_s: _abc.Iterable[_builtins.float] | None = ...,
        plant_rate_hz: _builtins.float | None = ...,
        phases: _abc.Iterable[Global___PhaseConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_plant_rate_hz", b"_plant_rate_hz", "plant_rate_hz", b"plant_rate_hz"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_plant_rate_hz", b"_plant_rate_hz", "description", b"description", "name", b"name", "omega0_rad_s", b"omega0_rad_s", "phases", b"phases", "plant_rate_hz", b"plant_rate_hz", "vehicle", b"vehicle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__plant_rate_hz: _TypeAlias = _typing.Literal["plant_rate_hz"]  # noqa: Y015
    _WhichOneofArgType__plant_rate_hz: _TypeAlias = _typing.Literal["_plant_rate_hz", b"_plant_rate_hz"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__plant_rate_hz) -> _WhichOneofReturnType__plant_rate_hz | None: ...

Global___MissionConfig: _TypeAlias = MissionConfig  # noqa: Y015
