#!/usr/bin/env python3
"""Compile flight/processes.toml + a host profile into systemd units.

The process table declares WHAT runs and its real-time contract (policy,
priority, core role, memory budget); the host profile declares WHERE roles
land on this board (core numbers, python path). This generator fuses them
into flatsat-<name>.service files plus a flatsat.target that Wants= them
all — the one-command constellation. Generated units are committed for
inspection (same pattern as the protobuf bindings) and installed by
tools/install-units.sh.

Usage:
  ~/venvs/flatsat-ml/bin/python tools/gen-units.py
  ... --profile tools/host-profiles/other-board.env
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path

import tomli

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TABLE = REPO_ROOT / "flight" / "processes.toml"
DEFAULT_PROFILE = REPO_ROOT / "tools" / "host-profiles" / "jetson-orin-nano.env"
DEFAULT_OUT = REPO_ROOT / "flight" / "units" / "generated"

GENERATED_HEADER = (
    "# GENERATED by tools/gen-units.py from flight/processes.toml + {profile}\n"
    "# Do not edit — change the table or profile and regenerate.\n"
)


@dataclass(frozen=True)
class ProcessSpec:
    """One row of the process table.

    Attributes:
        name: Short instance name; unit becomes flatsat-<name>.service.
        description: Human-readable purpose line.
        module: Python module run as ``python -m module``.
        args: Command-line arguments.
        after: Names of table processes to order after.
        rt_policy: "fifo" for SCHED_FIFO, or None for default scheduling.
        rt_priority: FIFO priority 1-99 (required when rt_policy is set).
        core_role: Abstract placement role resolved via the host profile,
            or None to run on the housekeeping CPU set.
        memory_max: systemd MemoryMax= budget string, or None.
    """

    name: str
    description: str
    module: str
    args: list[str] = field(default_factory=list)
    after: list[str] = field(default_factory=list)
    rt_policy: str | None = None
    rt_priority: int | None = None
    core_role: str | None = None
    memory_max: str | None = None


def load_table(path: Path) -> list[ProcessSpec]:
    """Parse the process table.

    Args:
        path: Path to processes.toml.

    Returns:
        The declared process specs, in table order.

    Raises:
        ValueError: If a process sets rt_policy without rt_priority.
    """
    with path.open("rb") as fh:
        data = tomli.load(fh)
    specs: list[ProcessSpec] = []
    for row in data.get("process", []):
        spec = ProcessSpec(
            name=str(row["name"]),
            description=str(row["description"]),
            module=str(row["module"]),
            args=[str(a) for a in row.get("args", [])],
            after=[str(a) for a in row.get("after", [])],
            rt_policy=str(row["rt_policy"]) if "rt_policy" in row else None,
            rt_priority=int(row["rt_priority"]) if "rt_priority" in row else None,
            core_role=str(row["core_role"]) if "core_role" in row else None,
            memory_max=str(row["memory_max"]) if "memory_max" in row else None,
        )
        if spec.rt_policy is not None and spec.rt_priority is None:
            raise ValueError(f"{spec.name}: rt_policy requires rt_priority")
        specs.append(spec)
    return specs


def load_profile(path: Path) -> dict[str, str]:
    """Parse a KEY=VALUE host profile file.

    Args:
        path: Path to the .env-style profile.

    Returns:
        Mapping of profile keys to values (comments/blank lines skipped).
    """
    profile: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        profile[key.strip()] = value.strip()
    return profile


def resolve_affinity(spec: ProcessSpec, profile: dict[str, str]) -> str:
    """Map a process's core role to concrete CPUs via the host profile.

    Args:
        spec: The process row.
        profile: The host profile mapping.

    Returns:
        A CPUAffinity= value string.

    Raises:
        KeyError: If the declared role has no entry in the profile.
    """
    if spec.core_role is not None:
        key = spec.core_role.upper()
        if key not in profile:
            raise KeyError(f"{spec.name}: role {spec.core_role!r} not in host profile")
        return profile[key]
    return profile.get("HOUSEKEEPING_CPUS", "")


def render_service(spec: ProcessSpec, profile: dict[str, str], profile_name: str) -> str:
    """Render one systemd service unit.

    Args:
        spec: The process row.
        profile: The host profile mapping.
        profile_name: Profile filename for the generated-header provenance.

    Returns:
        The unit file text.
    """
    exec_start = f"{profile['PYTHON']} -m {spec.module}"
    if spec.args:
        exec_start += " " + " ".join(spec.args)
    after_units = " ".join(f"flatsat-{dep}.service" for dep in spec.after)

    lines = [GENERATED_HEADER.format(profile=profile_name)]
    lines += ["[Unit]", f"Description={spec.description}", "PartOf=flatsat.target"]
    if after_units:
        lines.append(f"After={after_units}")
    lines += [
        "",
        "[Service]",
        f"ExecStart={exec_start}",
        f"WorkingDirectory={profile['WORKDIR']}",
        "Restart=on-failure",
        "RestartSec=1",
    ]
    affinity = resolve_affinity(spec, profile)
    if affinity:
        lines.append(f"CPUAffinity={affinity}")
    if spec.rt_policy is not None:
        lines.append(f"CPUSchedulingPolicy={spec.rt_policy}")
        lines.append(f"CPUSchedulingPriority={spec.rt_priority}")
    if spec.memory_max is not None:
        lines.append(f"MemoryMax={spec.memory_max}")
    lines += ["", "[Install]", "WantedBy=flatsat.target", ""]
    return "\n".join(lines)


def render_target(specs: list[ProcessSpec], profile_name: str) -> str:
    """Render the flatsat.target grouping unit.

    Args:
        specs: All process rows.
        profile_name: Profile filename for the generated-header provenance.

    Returns:
        The target file text.
    """
    wants = " ".join(f"flatsat-{s.name}.service" for s in specs)
    return "\n".join(
        [
            GENERATED_HEADER.format(profile=profile_name),
            "[Unit]",
            "Description=flatsat onboard segment (all processes)",
            f"Wants={wants}",
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "",
        ]
    )


def main() -> int:
    """Generate units from the table and profile.

    Returns:
        0 on success.
    """
    parser = argparse.ArgumentParser(description="Generate systemd units from processes.toml.")
    parser.add_argument("--table", type=Path, default=DEFAULT_TABLE)
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    specs = load_table(args.table)
    profile = load_profile(args.profile)
    args.out.mkdir(parents=True, exist_ok=True)

    for spec in specs:
        unit_path = args.out / f"flatsat-{spec.name}.service"
        unit_path.write_text(render_service(spec, profile, args.profile.name))
        print(f"wrote {unit_path.relative_to(REPO_ROOT)}")
    target_path = args.out / "flatsat.target"
    target_path.write_text(render_target(specs, args.profile.name))
    print(f"wrote {target_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
