#!/usr/bin/env python3
"""Compile vehicle + deployment + host profile into systemd units.

Three inputs, three separate concerns, joined only here:

  * ``config/vehicles/<name>.txtpb`` — WHAT the spacecraft is (sensors,
    control strategy). Portable across flight computers.
  * ``deployment.toml`` — HOW its processes run (RT policy,
    priority, core ROLE, memory budget). Portable across boards.
  * ``tools/host-profiles/<board>.env`` — WHERE roles land on this board
    (core numbers, interpreter path).

Adding a sensor to the vehicle file therefore yields a new unit with no
edit here and none in the deployment table (it inherits sensor defaults).
Generated units are committed for inspection, like the protobuf bindings,
and installed by tools/install-units.sh.

Usage:
  ~/venvs/flatsat-ml/bin/python tools/gen-units.py
  ... --vehicle config/vehicles/other.txtpb --profile tools/host-profiles/x.env
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:  # Python 3.11+
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))  # allow `python tools/gen-units.py` from anywhere

from flatsat.core.config import VehicleSpec, load_vehicle, which_impl  # noqa: E402

DEFAULT_VEHICLE = REPO_ROOT / "config" / "vehicles" / "flatsat_v1.txtpb"
DEFAULT_DEPLOYMENT = REPO_ROOT / "deployment.toml"
DEFAULT_PROFILE = REPO_ROOT / "tools" / "host-profiles" / "jetson-orin-nano.env"
DEFAULT_OUT = REPO_ROOT / "units" / "generated"

HEADER = (
    "# GENERATED by tools/gen-units.py\n"
    "#   vehicle:    {vehicle}\n"
    "#   deployment: {deployment}\n"
    "#   host:       {profile}\n"
    "# Do not edit — change an input and regenerate.\n"
)


def load_toml(path: Path) -> dict[str, Any]:
    """Parse a TOML file.

    Args:
        path: File to read.

    Returns:
        The parsed mapping.
    """
    with path.open("rb") as fh:
        data: dict[str, Any] = tomllib.load(fh)
    return data


def load_profile(path: Path) -> dict[str, str]:
    """Parse a KEY=VALUE host profile file.

    Args:
        path: Profile file.

    Returns:
        Mapping of profile keys to values.
    """
    profile: dict[str, str] = {}
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key, _, value = stripped.partition("=")
        profile[key.strip()] = value.strip()
    return profile


def resolve_affinity(core_role: str | None, profile: dict[str, str]) -> str:
    """Map a core role to concrete CPUs via the host profile.

    Args:
        core_role: Abstract role name, or None for housekeeping CPUs.
        profile: Host profile mapping.

    Returns:
        A ``CPUAffinity=`` value (empty string means unrestricted).

    Raises:
        KeyError: If the role has no entry in the profile.
    """
    if core_role is None:
        return profile.get("HOUSEKEEPING_CPUS", "")
    key = core_role.upper()
    if key not in profile:
        raise KeyError(f"core role {core_role!r} not in host profile")
    return profile[key]


def render_service(
    unit_name: str,
    description: str,
    exec_args: list[str],
    deploy: dict[str, Any],
    profile: dict[str, str],
    header: str,
    after: list[str] | None = None,
) -> str:
    """Render one systemd service unit.

    Args:
        unit_name: Unit basename after the ``flatsat-`` prefix.
        description: Unit description line.
        exec_args: Arguments after the interpreter (module and flags).
        deploy: Deployment attributes (rt_policy, rt_priority, core_role,
            memory_max).
        profile: Host profile mapping.
        header: Provenance header text.
        after: Unit basenames this one must start after.

    Returns:
        The unit file text.
    """
    lines = [header, "[Unit]", f"Description={description}", "PartOf=flatsat.target"]
    if after:
        lines.append("After=" + " ".join(f"flatsat-{dep}.service" for dep in after))
    lines += [
        "",
        "[Service]",
        f"ExecStart={profile['PYTHON']} {' '.join(exec_args)}",
        f"WorkingDirectory={profile['WORKDIR']}",
        "Environment=PYTHONUNBUFFERED=1",
        "Restart=on-failure",
        "RestartSec=1",
    ]
    if profile.get("RUN_USER"):
        # Flight code holds no root. Without this, systemd system units
        # run as root — and every "~" in the configuration (telemetry
        # archive, clean-shutdown marker) silently lands in /root.
        lines.append(f"User={profile['RUN_USER']}")
    if deploy.get("rt_policy"):
        # mlockall needs RLIMIT_MEMLOCK once the service is unprivileged;
        # grant it here, declaratively, like the scheduling policy.
        lines.append("LimitMEMLOCK=infinity")
    affinity = resolve_affinity(deploy.get("core_role"), profile)
    if affinity:
        lines.append(f"CPUAffinity={affinity}")
    if deploy.get("rt_policy"):
        lines.append(f"CPUSchedulingPolicy={deploy['rt_policy']}")
        lines.append(f"CPUSchedulingPriority={deploy['rt_priority']}")
    if deploy.get("memory_max"):
        lines.append(f"MemoryMax={deploy['memory_max']}")
    lines += ["", "[Install]", "WantedBy=flatsat.target", ""]
    return "\n".join(lines)


def main() -> int:
    """Generate units from the vehicle, deployment table, and host profile.

    Returns:
        0 on success.
    """
    parser = argparse.ArgumentParser(description="Generate systemd units for a vehicle.")
    parser.add_argument("--vehicle", type=Path, default=DEFAULT_VEHICLE)
    parser.add_argument("--deployment", type=Path, default=DEFAULT_DEPLOYMENT)
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    vehicle: VehicleSpec = load_vehicle(args.vehicle)
    deployment = load_toml(args.deployment)
    profile = load_profile(args.profile)
    header = HEADER.format(
        vehicle=args.vehicle.name, deployment=args.deployment.name, profile=args.profile.name
    )
    args.out.mkdir(parents=True, exist_ok=True)

    sensor_defaults = deployment.get("sensor_defaults", {})
    sensor_overrides = deployment.get("sensors", {})
    actuator_defaults = deployment.get("actuator_defaults", {})
    actuator_overrides = deployment.get("actuators", {})
    vehicle_rel = args.vehicle.relative_to(REPO_ROOT)
    written: list[str] = []

    for sensor in vehicle.sensors:
        name = sensor.name
        deploy = {**sensor_defaults, **sensor_overrides.get(name, {})}
        unit = render_service(
            unit_name=name,
            description=(
                f"{name} sensor daemon ({which_impl(sensor, 'options', name)}) — {vehicle.name}"
            ),
            exec_args=[
                "-m",
                "flatsat.apps.sensor_daemon",
                "--sensor",
                name,
                "--vehicle",
                str(vehicle_rel),
            ],
            deploy=deploy,
            profile=profile,
            header=header,
        )
        (args.out / f"flatsat-{name}.service").write_text(unit)
        written.append(f"flatsat-{name}.service")

    for actuator in vehicle.actuators:
        name = actuator.name
        deploy = {**actuator_defaults, **actuator_overrides.get(name, {})}
        unit = render_service(
            unit_name=name,
            description=(
                f"{name} actuator daemon ({which_impl(actuator, 'options', name)}) — {vehicle.name}"
            ),
            exec_args=[
                "-m",
                "flatsat.apps.actuator_daemon",
                "--actuator",
                name,
                "--vehicle",
                str(vehicle_rel),
            ],
            deploy=deploy,
            profile=profile,
            header=header,
        )
        (args.out / f"flatsat-{name}.service").write_text(unit)
        written.append(f"flatsat-{name}.service")

    mode_unit = render_service(
        unit_name="mode",
        description=f"system mode manager — {vehicle.name}",
        exec_args=[
            "-m",
            "flatsat.apps.mode_manager",
            "--vehicle",
            str(vehicle_rel),
        ],
        deploy=deployment.get("mode_manager", {}),
        profile=profile,
        header=header,
    )
    (args.out / "flatsat-mode.service").write_text(mode_unit)
    written.append("flatsat-mode.service")

    if len(vehicle.fdir.rules) > 0:
        fdir_unit = render_service(
            unit_name="fdir",
            description=f"FDIR limit checker ({len(vehicle.fdir.rules)} rules) — {vehicle.name}",
            exec_args=[
                "-m",
                "flatsat.apps.fdir",
                "--vehicle",
                str(vehicle_rel),
            ],
            deploy=deployment.get("fdir", {}),
            profile=profile,
            header=header,
        )
        (args.out / "flatsat-fdir.service").write_text(fdir_unit)
        written.append("flatsat-fdir.service")

    recorder_unit = render_service(
        unit_name="recorder",
        description=f"telemetry recorder — {vehicle.name}",
        exec_args=[
            "-m",
            "flatsat.apps.telemetry_recorder",
            "--vehicle",
            str(vehicle_rel),
        ],
        deploy=deployment.get("recorder", {}),
        profile=profile,
        header=header,
    )
    (args.out / "flatsat-recorder.service").write_text(recorder_unit)
    written.append("flatsat-recorder.service")

    control_deploy = deployment.get("control", {})
    control_unit = render_service(
        unit_name="adcs",
        description=(
            f"ADCS control loop ({which_impl(vehicle.control, 'strategy', 'control')}, "
            f"{which_impl(vehicle.control, 'objective', 'control')}) — {vehicle.name}"
        ),
        exec_args=[
            "-m",
            "flatsat.apps.control_loop",
            "--vehicle",
            str(vehicle_rel),
            "--duration",
            "0",
        ],
        deploy=control_deploy,
        profile=profile,
        header=header,
        after=[*(s.name for s in vehicle.sensors), *(a.name for a in vehicle.actuators)],
    )
    (args.out / "flatsat-adcs.service").write_text(control_unit)
    written.append("flatsat-adcs.service")

    target = "\n".join(
        [
            header,
            "[Unit]",
            f"Description=flatsat onboard segment — {vehicle.name}",
            "Wants=" + " ".join(written),
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "",
        ]
    )
    (args.out / "flatsat.target").write_text(target)

    # Prune units this vehicle no longer declares. Without this, renaming or
    # removing a sensor leaves a stale unit behind that install-units.sh
    # happily deploys — a process for a device the spacecraft does not have.
    keep = {*written, "flatsat.target"}
    for path in sorted(args.out.glob("flatsat*")):
        if path.name not in keep:
            path.unlink()
            print(f"pruned {path.relative_to(REPO_ROOT)} (not in {args.vehicle.name})")

    for name in sorted(keep):
        print(f"wrote {(args.out / name).relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
