# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flatsat/mode/mode_config.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flatsat/mode/mode_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66latsat/mode/mode_config.proto\x12\nflatsat.v1\"\x91\x01\n\nModeConfig\x12\x0c\n\x04\x61pps\x18\x01 \x03(\t\x12\x1a\n\rack_timeout_s\x18\x02 \x01(\x01H\x00\x88\x01\x01\x12\x18\n\x0bmin_dwell_s\x18\x03 \x01(\x01H\x01\x88\x01\x01\x12\x1d\n\x15\x63lean_shutdown_marker\x18\x04 \x01(\tB\x10\n\x0e_ack_timeout_sB\x0e\n\x0c_min_dwell_sb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flatsat.mode.mode_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODECONFIG']._serialized_start=47
  _globals['_MODECONFIG']._serialized_end=192
# @@protoc_insertion_point(module_scope)
