"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Mode-manager composition — the [mode] block of a vehicle file."""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ModeConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    APPS_FIELD_NUMBER: _builtins.int
    ACK_TIMEOUT_S_FIELD_NUMBER: _builtins.int
    MIN_DWELL_S_FIELD_NUMBER: _builtins.int
    CLEAN_SHUTDOWN_MARKER_FIELD_NUMBER: _builtins.int
    ack_timeout_s: _builtins.float
    """absent = 2.0"""
    min_dwell_s: _builtins.float
    """anti-flap, away-from-safety only; absent = 1.0"""
    clean_shutdown_marker: _builtins.str
    """File whose presence at boot means the previous shutdown was
    deliberate; consumed at startup. Empty = ~/flatsat-state/clean-shutdown.
    """
    @_builtins.property
    def apps(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Apps that must ack every mode transition; a missing ack is surfaced
        as a fault in ModeHealth.
        """

    def __init__(
        self,
        *,
        apps: _abc.Iterable[_builtins.str] | None = ...,
        ack_timeout_s: _builtins.float | None = ...,
        min_dwell_s: _builtins.float | None = ...,
        clean_shutdown_marker: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_ack_timeout_s", b"_ack_timeout_s", "_min_dwell_s", b"_min_dwell_s", "ack_timeout_s", b"ack_timeout_s", "min_dwell_s", b"min_dwell_s"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_ack_timeout_s", b"_ack_timeout_s", "_min_dwell_s", b"_min_dwell_s", "ack_timeout_s", b"ack_timeout_s", "apps", b"apps", "clean_shutdown_marker", b"clean_shutdown_marker", "min_dwell_s", b"min_dwell_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__ack_timeout_s: _TypeAlias = _typing.Literal["ack_timeout_s"]  # noqa: Y015
    _WhichOneofArgType__ack_timeout_s: _TypeAlias = _typing.Literal["_ack_timeout_s", b"_ack_timeout_s"]  # noqa: Y015
    _WhichOneofReturnType__min_dwell_s: _TypeAlias = _typing.Literal["min_dwell_s"]  # noqa: Y015
    _WhichOneofArgType__min_dwell_s: _TypeAlias = _typing.Literal["_min_dwell_s", b"_min_dwell_s"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ack_timeout_s) -> _WhichOneofReturnType__ack_timeout_s | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__min_dwell_s) -> _WhichOneofReturnType__min_dwell_s | None: ...

Global___ModeConfig: _TypeAlias = ModeConfig  # noqa: Y015
